const tematicasData = {
    "biblia": {
        titulo: "📖 Biblia Completa",
        preguntas: [
            { pregunta: "¿Cómo se llama el guía de esta aventura bíblica?", opciones: ["Melki", "Josué", "David", "Moisés"], correcta: 0 },
            { pregunta: "¿Cuántos días y noches llovió durante el diluvio?", opciones: ["30 días", "40 días", "50 días", "70 días"], correcta: 1 },
            { pregunta: "¿Quién fue tragado por un gran pez?", opciones: ["Jonás", "Pedro", "Daniel", "Abraham"], correcta: 0 },
            { pregunta: "¿Cuántos mandamientos le dio Dios a Moisés?", opciones: ["5", "7", "10", "12"], correcta: 2 },
            { pregunta: "¿En qué río fue bautizado Jesús?", opciones: ["Nilo", "Jordán", "Éufrates", "Tigris"], correcta: 1 },
            { pregunta: "¿Quién derrotó al gigante Goliat?", opciones: ["Saúl", "Salomón", "David", "Sansón"], correcta: 2 },
            { pregunta: "¿Cuál es el primer libro de la Biblia?", opciones: ["Éxodo", "Génesis", "Levítico", "Mateo"], correcta: 1 },
            { pregunta: "¿Quién construyó el arca?", opciones: ["Abraham", "Noé", "Moisés", "Jacob"], correcta: 1 },
            { pregunta: "¿Cuántos discípulos principales tenía Jesús?", opciones: ["10", "12", "7", "40"], correcta: 1 },
            { pregunta: "¿En qué ciudad nació Jesús?", opciones: ["Jerusalén", "Nazaret", "Belén", "Jericó"], correcta: 2 },
            { pregunta: "¿Qué usó David para vencer a Goliat?", opciones: ["Una espada", "Una honda y piedras", "Una lanza", "Un arco"], correcta: 1 },
            { pregunta: "¿Quién fue vendido por sus hermanos como esclavo?", opciones: ["José", "Benjamín", "Judá", "Rubén"], correcta: 0 },
            { pregunta: "¿Cuál es el último libro de la Biblia?", opciones: ["Hebreos", "Apocalipsis", "Hechos", "Judas"], correcta: 1 },
            { pregunta: "¿Quién abrió el Mar Rojo con su vara?", opciones: ["Aarón", "Moisés", "Josué", "Gedeón"], correcta: 1 },
            { pregunta: "¿Qué animal habló con Eva en el Edén?", opciones: ["Un ave", "Una serpiente", "Un león", "Un cordero"], correcta: 1 },
            { pregunta: "¿Cuántos días tardó Dios en crear el mundo según el Génesis?", opciones: ["6 días", "7 días", "10 días", "1 día"], correcta: 0 },
            { pregunta: "¿Quién sobrevivió en el foso de los leones?", opciones: ["Sadrac", "Daniel", "Ezequiel", "Jeremías"], correcta: 1 },
            { pregunta: "¿Quién recibió la sabiduría concedida por Dios?", opciones: ["David", "Salomón", "Saúl", "Samuel"], correcta: 1 },
            { pregunta: "¿Qué mar cruzaron los israelitas huyendo de Egipto?", opciones: ["Mar Muerto", "Mar Rojo", "Mar Mediterráneo", "Mar de Galilea"], correcta: 1 },
            { pregunta: "¿Qué señal puso Dios tras el diluvio como promesa?", opciones: ["Un arcoíris", "Una estrella", "Un fuego", "Una nube"], correcta: 0 },
            { pregunta: "¿Quién fue la madre terrenal de Jesús?", opciones: ["Marta", "María", "Isabel", "Ana"], correcta: 1 },
            { pregunta: "¿En qué monte le dio Dios los 10 mandamientos a Moisés?", opciones: ["Monte Olivos", "Monte Sinaí", "Monte Carmelo", "Monte Ararat"], correcta: 1 },
            { pregunta: "¿Quién fue el hombre más fuerte según la Biblia?", opciones: ["Sansón", "Saúl", "David", "Roboam"], correcta: 0 },
            { pregunta: "¿Qué alimento cayó del cielo para alimentar a Israel en el desierto?", opciones: ["Maná", "Trigo", "Pan dulce", "Frutas"], correcta: 0 },
            { pregunta: "¿Quién negó a Jesús tres veces antes del canto del gallo?", opciones: ["Juan", "Pedro", "Tomás", "Santiago"], correcta: 1 },
            { pregunta: "¿Qué profesión tenía Mateo antes de seguir a Jesús?", opciones: ["Pescador", "Recaudador de impuestos", "Carpintero", "Pastor"], correcta: 1 },
            { pregunta: "¿Quién fue el hombre más longevo según la Biblia?", opciones: ["Matusalén", "Adán", "Noé", "Enoc"], correcta: 0 },
            { pregunta: "¿Quién tradujo la ley e instruyó al pueblo al regresar del exilio?", opciones: ["Esdras", "Nehemías", "Zacarías", "Malaquías"], correcta: 0 },
            { pregunta: "¿Qué reina visitó al rey Salomón para probar su sabiduría?", opciones: ["Reina de Sabá", "Reina Ester", "Reina Jezabel", "Reina Vasti"], correcta: 0 },
            { pregunta: "¿Qué ciudad cayó tras dar 7 vueltas y tocar las trompetas?", opciones: ["Jericó", "Babilonia", "Nínive", "Sodoma"], correcta: 0 },
            { pregunta: "¿Quién acompañó a Moisés a hablar con el Faraón?", opciones: ["Aarón", "Josué", "Caleb", "Jetro"], correcta: 0 },
            { pregunta: "¿Qué personaje bíblico perdió todo pero mantuvo su fe?", opciones: ["Job", "Jonás", "Elías", "Isaías"], correcta: 0 },
            { pregunta: "¿Cómo se llama el mar donde Jesús caminó sobre las aguas?", opciones: ["Mar Rojo", "Mar de Galilea", "Mar Muerto", "Mar Negro"], correcta: 1 },
            { pregunta: "¿Quién fue el primer rey de Israel?", opciones: ["David", "Saúl", "Salomón", "Samuel"], correcta: 1 },
            { pregunta: "¿Cuántas veces perdonar según las enseñanzas de Jesús?", opciones: ["7 veces", "70 veces 7", "10 veces", "3 veces"], correcta: 1 },
            { pregunta: "¿Quién escribió la mayoría de las epístolas del Nuevo Testamento?", opciones: ["Pedro", "Pablo", "Juan", "Lucas"], correcta: 1 },
            { pregunta: "¿Qué milagro hizo Jesús en las bodas de Caná?", opciones: ["Sanar a un ciego", "Convertir agua en vino", "Multiplicar peces", "Calmar la tempestad"], correcta: 1 },
            { pregunta: "¿Quién fue llevado al cielo en un carro de fuego?", opciones: ["Elías", "Eliseo", "Ezequiel", "Moisés"], correcta: 0 },
            { pregunta: "¿En qué convirtió Moisés las aguas del Nilo ante el Faraón?", opciones: ["Vino", "Sangre", "Aceite", "Lodo"], correcta: 1 },
            { pregunta: "¿Quién fue la reina judía que salvó a su pueblo en Persia?", opciones: ["Ester", "Rut", "Ana", "Débora"], correcta: 0 },
            { pregunta: "¿Qué fruto del Espíritu Santo se menciona primero en Gálatas 5?", opciones: ["Paz", "Amor", "Gozo", "Paciencia"], correcta: 1 },
            { pregunta: "¿En qué idioma se escribió la mayor parte del Antiguo Testamento?", opciones: ["Griego", "Hebreo", "Latín", "Arameo"], correcta: 1 },
            { pregunta: "¿Quién fue el hermano de Moisés?", opciones: ["Aarón", "Josué", "Caleb", "Leví"], correcta: 0 },
            { pregunta: "¿Quién fue la madre de Samuel?", opciones: ["Ana", "Penina", "Sara", "Raquel"], correcta: 0 },
            { pregunta: "¿Cuál era la profesión de Lucas?", opciones: ["Médico", "Pescador", "Sacerdote", "Soldado"], correcta: 0 },
            { pregunta: "¿A quién resucitó Jesús en Betania tras llevar 4 días muerto?", opciones: ["Lázaro", "Esteban", "Santiago", "Simón"], correcta: 0 },
            { pregunta: "¿Qué ciudad fue destruida junto con Gomorra?", opciones: ["Sodoma", "Jericó", "Nínive", "Tiro"], correcta: 0 },
            { pregunta: "¿Dónde vivió Adán y Eva originalmente?", opciones: ["Jardín del Edén", "Monte Sinaí", "Canaán", "Tierra de Uz"], correcta: 0 },
            { pregunta: "¿Qué profeta fue arrojado al foso de los leones?", opciones: ["Daniel", "Jeremías", "Isaías", "Oseas"], correcta: 0 },
            { pregunta: "¿Qué rey pidió la cabeza de Juan el Bautista?", opciones: ["Herodes", "Pilato", "César", "Agripa"], correcta: 0 },
            { pregunta: "¿Quién guio a los israelitas hacia Canaán tras la muerte de Moisés?", opciones: ["Josué", "Caleb", "Gedeón", "Aarón"], correcta: 0 },
            { pregunta: "¿Qué ciego fue sanado por Jesús a la salida de Jericó?", opciones: ["Bartimeo", "Lázaro", "Zaqueo", "Nicodemo"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba el hombre de pequeña estatura que subió a un árbol para ver a Jesús?", opciones: ["Zaqueo", "Bartimeo", "Mateo", "Simón"], correcta: 0 },
            { pregunta: "¿Qué apóstol dudó de la resurrección de Jesús hasta ver sus heridas?", opciones: ["Tomás", "Felipe", "Andrés", "Judas"], correcta: 0 },
            { pregunta: "¿Cuántas tribus componían el pueblo de Israel?", opciones: ["12", "10", "7", "14"], correcta: 0 },
            { pregunta: "¿Quién construyó el primer Templo de Jerusalén?", opciones: ["Salomón", "David", "Esdras", "Zorobabel"], correcta: 0 },
            { pregunta: "¿Qué ave envió Noé primero desde el arca?", opciones: ["Un cuervo", "Una paloma", "Un águila", "Una golondrina"], correcta: 0 },
            { pregunta: "¿En qué monte descansó el arca de Noé?", opciones: ["Monte Ararat", "Monte Sinaí", "Monte Carmelo", "Monte Tabor"], correcta: 0 },
            { pregunta: "¿Quién interpretó el sueño del Faraón sobre las 7 vacas flacas?", opciones: ["José", "Daniel", "Moisés", "Samuel"], correcta: 0 },
            { pregunta: "¿Quién derrotó a los madianitas con solo 300 hombres?", opciones: ["Gedeón", "Sansón", "Saúl", "Barac"], correcta: 0 },
            { pregunta: "¿Cuál fue el primer milagro público de Jesús según el evangelio de Juan?", opciones: ["Agua en vino", "Sanar al paralítico", "Multiplicar panes", "Caminar sobre agua"], correcta: 0 },
            { pregunta: "¿En qué lugar fue arrestado Jesús?", opciones: ["Huerto de Getsemaní", "Monte de los Olivos", "Templo", "Casa de Caifás"], correcta: 0 },
            { pregunta: "¿Qué juez bíblico tenía una fuerza extraordinaria en su cabello?", opciones: ["Sansón", "Gedeón", "Jefté", "Samuel"], correcta: 0 },
            { pregunta: "¿Qué mujer fue esposa de Isaac?", opciones: ["Rebeca", "Sara", "Raquel", "Lea"], correcta: 0 },
            { pregunta: "¿Quién fue el padre de muchos pueblos según la promesa de Dios?", opciones: ["Abraham", "Isaac", "Jacob", "Noé"], correcta: 0 },
            { pregunta: "¿Qué ángel le anunció a María que daría a luz a Jesús?", opciones: ["Gabriel", "Miguel", "Rafael", "Uriel"], correcta: 0 },
            { pregunta: "¿Cuántos panes y peces usó Jesús para alimentar a la multitud?", opciones: ["5 panes y 2 peces", "7 panes y 3 peces", "3 panes y 5 peces", "12 panes y 2 peces"], correcta: 0 },
            { pregunta: "¿Qué mar se dividió para que el pueblo de Israel caminara en seco?", opciones: ["Mar Rojo", "Mar Muerto", "Mar de Galilea", "Mar Mediterráneo"], correcta: 0 },
            { pregunta: "¿Qué profeta fue tragado por un gran pez por no ir a Nínive?", opciones: ["Jonás", "Amós", "Miqueas", "Joel"], correcta: 0 },
            { pregunta: "¿Quién fue el primer mártir cristiano registrado en los Hechos?", opciones: ["Esteban", "Felipe", "Santiago", "Pedro"], correcta: 0 },
            { pregunta: "¿En qué isla estuvo exiliado el apóstol Juan cuando escribió Apocalipsis?", opciones: ["Patmos", "Chipre", "Creta", "Malta"], correcta: 0 },
            { pregunta: "¿Quién fue el gobernador romano que sentenció a Jesús?", opciones: ["Poncio Pilato", "Herodes", "Félix", "Festos"], correcta: 0 },
            { pregunta: "¿Qué regalo llevaron los sabios del oriente al niño Jesús?", opciones: ["Oro, incienso y mirra", "Plata, seda y especias", "Pan, vino y aceite", "Joyas, telas y perfume"], correcta: 0 },
            { pregunta: "¿Qué rey persa decretó el regreso de los judíos a Jerusalén?", opciones: ["Ciro", "Darío", "Jerjes", "Artajerjes"], correcta: 0 },
            { pregunta: "¿Quién fue la esposa de Jacob a quien más amaba?", opciones: ["Raquel", "Lea", "Zilpa", "Bilhá"], correcta: 0 },
            { pregunta: "¿Qué mandamiento es el primero con promesa?", opciones: ["Honra a tu padre y a tu madre", "No hurtarás", "No matarás", "Amaras a Dios sobre todas las cosas"], correcta: 0 },
            { pregunta: "¿Qué acontecimiento ocurrió en Pentecostés?", opciones: ["Descenso del Espíritu Santo", "La resurrección", "La ascensión", "La transfiguración"], correcta: 0 },
            { pregunta: "¿Qué instrumento tocaba David para calmar al rey Saúl?", opciones: ["El arpa", "La flauta", "El tambor", "La trompeta"], correcta: 0 },
            { pregunta: "¿Qué ciudad reconstruyó Nehemías liderando al pueblo?", opciones: ["Jerusalén", "Jericó", "Samaria", "Damasco"], correcta: 0 },
            { pregunta: "¿Qué reina desafío al profeta Elías?", opciones: ["Jezabel", "Vasti", "Atalía", "Herodías"], correcta: 0 },
            { pregunta: "¿Qué significa el nombre Emmanuel?", opciones: ["Dios con nosotros", "Dios es amor", "El Salvador", "Dios es fuerte"], correcta: 0 },
            { pregunta: "¿Quién ayudó a Jesús a cargar la cruz camino al Calvario?", opciones: ["Simón de Cirene", "José de Arimatea", "Nicodemo", "Juan"], correcta: 0 },
            { pregunta: "¿En qué río se lavó Naamán para ser sanado de lepra?", opciones: ["Jordán", "Abana", "Farfar", "Nilo"], correcta: 0 },
            { pregunta: "¿Quién fue el padre de Juan el Bautista?", opciones: ["Zacarías", "Simeón", "José", "Joaquín"], correcta: 0 },
            { pregunta: "¿Quién fue la profetisa que juzgó a Israel bajo una palmera?", opciones: ["Débora", "Jael", "Miriam", "Hulda"], correcta: 0 },
            { pregunta: "¿Qué le dio Jacob a su hijo José como muestra de su afecto?", opciones: ["Una túnica de colores", "Un anillo de oro", "Un rebaño de ovejas", "Una corona"], correcta: 0 },
            { pregunta: "¿Qué nombre le puso Dios a Jacob tras luchar con el ángel?", opciones: ["Israel", "Judá", "Efraín", "Manasés"], correcta: 0 },
            { pregunta: "¿Cuántos años vagó el pueblo de Israel por el desierto?", opciones: ["40 años", "50 años", "70 años", "30 años"], correcta: 0 },
            { pregunta: "¿En qué monte desafió Elías a los profetas de Baal?", opciones: ["Monte Carmelo", "Monte Sinaí", "Monte Tabor", "Monte Hermón"], correcta: 0 },
            { pregunta: "¿Quién compró a José en Egipto?", opciones: ["Potifar", "El Faraón", "Jotam", "Putiel"], correcta: 0 },
            { pregunta: "¿Quién se convirtió en estatua de sal al mirar atrás hacia Sodoma?", opciones: ["La esposa de Lot", "La hija de Lot", "La esposa de Abraham", "La criada de Agar"], correcta: 0 },
            { pregunta: "¿Qué profeta vio una visión de un valle de huesos secos que cobraban vida?", opciones: ["Ezequiel", "Isaías", "Jeremías", "Daniel"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba el monte donde Jesús fue crucificado?", opciones: ["Gólgota", "Olivos", "Sinaí", "Sión"], correcta: 0 },
            { pregunta: "¿Quién era la abuela del joven Timoteo destacada por su fe?", opciones: ["Loida", "Eunice", "Priscila", "Lidia"], correcta: 0 },
            { pregunta: "¿Qué oficio tenía Pablo además de predicar el evangelio?", opciones: ["Hacer tiendas de acampar", "Pescador", "Carpintero", "Agricultor"], correcta: 0 },
            { pregunta: "¿Quién escribió el libro de los Hechos de los Apóstoles?", opciones: ["Lucas", "Pablo", "Pedro", "Juan"], correcta: 0 },
            { pregunta: "¿En qué lugar oraba Jesús cuando su sudor fue como gotas de sangre?", opciones: ["Getsemaní", "Betania", "Cafarnaúm", "Emaús"], correcta: 0 },
            { pregunta: "¿Qué mujer tocó el borde del manto de Jesús creyendo que sería sanada?", opciones: ["La mujer con flujo de sangre", "La mujer cananea", "La suegra de Pedro", "María Magdalena"], correcta: 0 },
            { pregunta: "¿Qué rey sabio escribió la mayoría de los Proverbios?", opciones: ["Salomón", "David", "Ezequías", "Josías"], correcta: 0 },
            { pregunta: "¿Quién fue el joven rey que reformó Israel y halló el libro de la Ley?", opciones: ["Josías", "Manasés", "Ezequías", "Joás"], correcta: 0 }
        ]
    },
    "naturaleza": {
        titulo: "🌿 Cuidado de la Creación y Naturaleza",
        preguntas: [
            { pregunta: "¿Qué creó Dios en el primer día según el Génesis?", opciones: ["La luz", "Los animales", "El sol", "Las plantas"], correcta: 0 },
            { pregunta: "¿Cómo debemos cuidar la creación de Dios?", opciones: ["Tirando basura", "Reciclando y cuidando los animales", "Cortando árboles", "Desperdiciando agua"], correcta: 1 },
            { pregunta: "¿En qué libro bíblico se narra la creación del mundo?", opciones: ["Éxodo", "Génesis", "Salmos", "Apocalipsis"], correcta: 1 },
            { pregunta: "¿Qué ave envió Noé y regresó con una rama de olivo?", opciones: ["Un cuervo", "Una paloma", "Un águila", "Una golondrina"], correcta: 1 },
            { pregunta: "¿Qué río del Edén se menciona en la Biblia?", opciones: ["Nilo", "Gihón", "Jordán", "Amazonas"], correcta: 1 },
            { pregunta: "¿Qué insecto es ejemplo de trabajo en el libro de Proverbios?", opciones: ["La abeja", "La hormiga", "El grillo", "La mariposa"], correcta: 1 },
            { pregunta: "¿Quién nombró a todos los animales en el Edén?", opciones: ["Noé", "Adán", "Moisés", "Melki"], correcta: 1 },
            { pregunta: "¿Qué árbol es mencionado frecuentemente como símbolo de rectitud?", opciones: ["El olivo", "El cedro del Líbano", "La palmera", "El pino"], correcta: 1 },
            { pregunta: "¿Qué representan las plantas según las parábolas de Jesús?", opciones: ["El crecimiento de la fe", "El dinero", "El viento", "Las piedras"], correcta: 0 },
            { pregunta: "¿Qué animal representó la paz en el bautismo de Jesús?", opciones: ["Un cordero", "Una paloma", "Un pez", "Un ciervo"], correcta: 1 },
            { pregunta: "¿Por qué es importante cuidar los mares y ríos?", opciones: ["Porque son creación de Dios y hogar de especies", "Para jugar con botes", "No importa si se contaminan", "Para botar plástico"], correcta: 0 },
            { pregunta: "¿Qué día creó Dios los peces del mar y las aves del cielo?", opciones: ["Quinto día", "Tercer día", "Sexto día", "Segundo día"], correcta: 0 },
            { pregunta: "¿Qué día creó Dios a los animales terrestres y al ser humano?", opciones: ["Sexto día", "Cuarto día", "Séptimo día", "Tercer día"], correcta: 0 },
            { pregunta: "¿Qué vegetal o planta usaban en Israel para dar luz con lámparas?", opciones: ["Aceite de olivo", "Aceite de girasol", "Aceite de maíz", "Aceite de palma"], correcta: 0 },
            { pregunta: "¿Qué representa la semilla de mostaza en la enseñanza bíblica?", opciones: ["Una fe pequeña que crece enormemente", "La comida del desierto", "Un árbol seco", "El dinero"], correcta: 0 },
            { pregunta: "¿Qué debemos hacer con los desechos plásticos en las playas?", opciones: ["Recogerlos y reciclar", "Dejarlos en la arena", "Quemarlos en la orilla", "Tirarlos al mar"], correcta: 0 },
            { pregunta: "¿Qué beneficio nos brindan los árboles de la Creación?", opciones: ["Limpian el aire, dan sombra y fruto", "Hacen daño", "Ocupan espacio innecesario", "Producen plástico"], correcta: 0 },
            { pregunta: "¿Qué ley ecológica enseñó Dios a los israelitas sobre la tierra agrícola?", opciones: ["Dejar descansar la tierra el séptimo año", "Quemar todo cada mes", "Usar químicos tóxicos", "Talar todos los árboles"], correcta: 0 },
            { pregunta: "¿Qué animal bíblico habló al profeta Balaam tras ver al ángel?", opciones: ["Una asna", "Un camello", "Un caballo", "Un buey"], correcta: 0 },
            { pregunta: "¿Qué animal se menciona como símbolo del buen pastor que cuida su rebaño?", opciones: ["La oveja", "El lobo", "El león", "El oso"], correcta: 0 },
            { pregunta: "¿Qué aves alimentaron al profeta Elías junto al arroyo de Querit?", opciones: ["Los cuervos", "Las palomas", "Las águilas", "Los gorriones"], correcta: 0 },
            { pregunta: "¿En qué día separó Dios las aguas de la expansión en el Génesis?", opciones: ["Segundo día", "Primer día", "Tercer día", "Cuarto día"], correcta: 0 },
            { pregunta: "¿Qué elemento de la naturaleza calmó Jesús con una sola palabra en el mar?", opciones: ["La tempestad y el viento", "El fuego", "Un terremoto", "Un volcán"], correcta: 0 },
            { pregunta: "¿Qué flor del campo usó Jesús como ejemplo del cuidado de Dios hacia nosotros?", opciones: ["Los lirios del campo", "Las rosas", "Los girasoles", "Los claveles"], correcta: 0 },
            { pregunta: "¿Qué debemos hacer ante la tala indiscriminada de bosques?", opciones: ["Reforestar y sembrar nuevos árboles", "Apoyar la tala", "Ignorar la situación", "Quemar las hojas"], correcta: 0 },
            { pregunta: "¿Qué función cumplen los manglares en las costas e islas?", opciones: ["Proteger la costa contra erosión y albergar vida marina", "Acumular basura", "Tapar la vista", "Dañar el agua"], correcta: 0 },
            { pregunta: "¿Qué animal es recordado en la historia del Arca por traer esperanza?", opciones: ["La paloma", "El cuervo", "El búho", "El halcón"], correcta: 0 },
            { pregunta: "¿Qué día creó Dios el Sol, la Luna y las Estrellas?", opciones: ["Cuarto día", "Segundo día", "Primer día", "Quinto día"], correcta: 0 },
            { pregunta: "¿Por qué debemos ahorrar el agua en nuestra comunidad?", opciones: ["Porque es un recurso vital bendecido por Dios", "Para pagar menos únicamente", "No hace falta ahorrar", "Porque no sirve para nada"], correcta: 0 },
            { pregunta: "¿Qué encomendó Dios al ser humano con respecto al Edén?", opciones: ["Labrarlo y cuidarlo", "Destruirlo", "Pavimentarlo", "Ignorarlo"], correcta: 0 },
            { pregunta: "¿Qué animal en el Apocalipsis representa fuerza y victoria?", opciones: ["El León de la tribu de Judá", "El Águila dorada", "El Buey", "El Cordero fuerte"], correcta: 0 },
            { pregunta: "¿Qué árbol seco hizo secar Jesús al no encontrar fruto en él?", opciones: ["La higuera", "El olivo", "El granado", "La vid"], correcta: 0 },
            { pregunta: "¿Qué fruta se menciona como fruto de la promesa en Canaán?", opciones: ["Las uvas gigantes", "Las manzanas", "Las naranjas", "Los plátanos"], correcta: 0 },
            { pregunta: "¿Qué animal marino preparó Dios para recibir a Jonás?", opciones: ["Un gran pez", "Un tiburón", "Un pulpo", "Una ballena azul"], correcta: 0 },
            { pregunta: "¿Cómo podemos reducir la contaminación en nuestro vecindario?", opciones: ["No botar basura y reutilizar", "Quemar llantas", "Tirar aceite al drenaje", "Dejar la luz encendida"], correcta: 0 },
            { pregunta: "¿Qué significa ser un buen mayordomo de la naturaleza?", opciones: ["Administrar y cuidar los recursos naturales", "Gastar todo sin pensar", "Vender los bosques", "Contaminar los ríos"], correcta: 0 },
            { pregunta: "¿Qué animal representa la astucia en las parábolas bíblicas?", opciones: ["La serpiente", "El zorro", "El lobo", "El gato"], correcta: 0 },
            { pregunta: "¿Qué representa el árbol plantado junto a corrientes de agua en el Salmo 1?", opciones: ["El hombre bendecido que confía en Dios", "Un cactus seco", "Un matorral espinoso", "Un hongo silvestre"], correcta: 0 },
            { pregunta: "¿Qué líquido usó Dios para limpiar la tierra en tiempos de Noé?", opciones: ["El agua del diluvio", "El viento", "El fuego", "La nieve"], correcta: 0 },
            { pregunta: "¿Qué insecto utilizó Salomón como ejemplo de disciplina para el perezoso?", opciones: ["La hormiga", "La pulga", "El caracol", "La garrapata"], correcta: 0 },
            { pregunta: "¿Qué gas vital producen las plantas mediante la fotosíntesis?", opciones: ["Oxígeno", "Dióxido de carbono", "Metano", "Nitrógeno"], correcta: 0 },
            { pregunta: "¿Por qué no debemos arrojar aceites usados por los sifones?", opciones: ["Contamina miles de litros de agua dulce y ríos", "No pasa nada", "Huele feo únicamente", "Limpia los tubos"], correcta: 0 },
            { pregunta: "¿Qué tipo de energía renovable aprovecha el sol?", opciones: ["Energía solar", "Energía eólica", "Energía fósil", "Energía nuclear"], correcta: 0 },
            { pregunta: "¿Qué tipo de energía aprovecha la fuerza del viento?", opciones: ["Energía eólica", "Energía solar", "Energía hidráulica", "Energía geotérmica"], correcta: 0 },
            { pregunta: "¿Cómo ayudan las abejas a las flores y frutos en la naturaleza?", opciones: ["Mediante la polinización", "Haciendo ruido", "Comiendo hojas", "Ninguna función"], correcta: 0 },
            { pregunta: "¿Qué animal representa la mansedumbre en la Biblia?", opciones: ["El cordero", "El tigre", "El perro", "El leopardo"], correcta: 0 },
            { pregunta: "¿Qué ocurre si se destruye el hábitat de los animales silvestres?", opciones: ["Se extinguen especies y se altera el ecosistema", "Aumenta la comida", "No ocurre nada", "Se adaptan de inmediato"], correcta: 0 },
            { pregunta: "¿Qué debemos hacer con las pilas y baterías usadas?", opciones: ["Llevarlas a puntos de reciclaje especial", "Tirarlas a la basura común", "Lanzarlas al mar", "Enterrarlas en el jardín"], correcta: 0 },
            { pregunta: "¿Qué planeta creó Dios como nuestro hogar?", opciones: ["La Tierra", "Marte", "Júpiter", "Venus"], correcta: 0 },
            { pregunta: "¿Qué capa de la atmósfera nos protege de la radiación ultravioleta?", opciones: ["La capa de ozono", "Las nubes", "La lluvia", "El viento"], correcta: 0 },
            { pregunta: "¿Qué debemos hacer para cuidar a los animales domésticos?", opciones: ["Darles alimento, agua, refugio y cariño", "Tenerlos amarrados sin agua", "Abandonarlos", "Hacerlos trabajar sin descanso"], correcta: 0 },
            { pregunta: "¿Qué acción sencilla ahorra energía eléctrica en casa?", opciones: ["Apagar luces y electrodomésticos que no se usen", "Dejar la TV encendida siempre", "Usar focos ineficientes", "Dejar cargadores conectados"], correcta: 0 },
            { pregunta: "¿Qué ave se menciona en los Salmos cuya juventud se renueva?", opciones: ["El águila", "El halcón", "El cóndor", "El pelícano"], correcta: 0 },
            { pregunta: "¿Qué es el abono orgánico o compost?", opciones: ["Abono natural hecho de residuos biodegradables", "Quemar plástico", "Químicos sintéticos", "Tirar basura"], correcta: 0 },
            { pregunta: "¿Por qué son importantes los arrecifes de coral en el mar?", opciones: ["Son refugio y crianza para miles de especies marinas", "Son rocas bonitas nada más", "No importan", "Producen petroleo"], correcta: 0 },
            { pregunta: "¿Cómo se previenen incendios en zonas forestales?", opciones: ["Evitando fogatas y no dejando vidrios en el campo", "Tirando fósforos", "Quemando maleza seca", "Dejar latas de gas"], correcta: 0 },
            { pregunta: "¿Qué representa la lluvia en los pasajes bíblicos de bendición?", opciones: ["Prosperidad y vida para las cosechas", "Un castigo", "Frío extremo", "Pérdida de tierra"], correcta: 0 },
            { pregunta: "¿Qué planta le dio sombra al profeta Jonás fuera de Nínive?", opciones: ["Una calabacera", "Un roble", "Una palmera", "Un pino"], correcta: 0 },
            { pregunta: "¿Qué animal pequeño habita en las peñas según el libro de Proverbios?", opciones: ["El damán o conejo de roca", "El zorro", "El castor", "La ardilla"], correcta: 0 },
            { pregunta: "¿Qué beneficio tiene sembrar huertos comunitarios o escolares?", opciones: ["Aprender a cultivar alimentos sanos y valorar la tierra", "Perder tiempo", "Gastar dinero", "Ninguno"], correcta: 0 },
            { pregunta: "¿Qué pacto de Dios se reflejó con el arcoíris?", opciones: ["Que no volvería a destruir la Tierra con un diluvio", "Que siempre habría sol", "Que llovería oro", "Que no habría noche"], correcta: 0 },
            { pregunta: "¿Por qué debemos reducir el uso de plástico desechable?", opciones: ["Tarda siglos en degradarse y daña la fauna marina", "Se rompe rápido", "Es muy liviano", "No hay razón"], correcta: 0 },
            { pregunta: "¿Qué ave corre velozmente en el desierto y se menciona en Job?", opciones: ["El avestruz", "El dromedario", "La gacela", "El guepardo"], correcta: 0 },
            { pregunta: "¿Qué hizo Dios el séptimo día tras completar la Creación?", opciones: ["Reposó y lo santificó", "Siguió creando", "Destruyó todo", "Creó los océanos"], correcta: 0 },
            { pregunta: "¿Qué fuente de agua dulce nos sostiene en las comunidades?", opciones: ["Ríos, manantiales y acuíferos", "Agua salada", "Lluvia ácida", "Ninguna"], correcta: 0 },
            { pregunta: "¿Qué animal es famoso por construir represas en arroyos?", opciones: ["El castor", "La nutria", "El capibara", "El pato"], correcta: 0 },
            { pregunta: "¿Qué conducta es correcta en una reserva ecoturística?", opciones: ["Cuidar las plantas, animales y no dejar basura", "Arrancar flores", "Hacer ruido con parlantes", "Molestar la fauna"], correcta: 0 },
            { pregunta: "¿Qué líquido extraído de los panales es alabado en la Biblia?", opciones: ["La miel", "El vinagre", "El jugo de uva", "El suero"], correcta: 0 },
            { pregunta: "¿Qué enseñanza da Jesús sobre las aves del cielo?", opciones: ["Que Dios las alimenta sin que ellas almacenen en graneros", "Que deben trabajar duro", "Que no le importan a Dios", "Que son peligrosas"], correcta: 0 },
            { pregunta: "¿Qué valor representa el cuidado ambiental en el grupo Generación Oasis?", opciones: ["Honrar al Creador mediante el cuidado de su obra", "Una moda pasajera", "Un compromiso sin valor", "Solo una clase de ciencia"], correcta: 0 },
            { pregunta: "¿Qué regla ecológica promueve Reducir, Reutilizar y Reciclar?", opciones: ["La regla de las 3 R", "La regla de oro", "Las 5 S", "El ciclo del agua"], correcta: 0 },
            { pregunta: "¿Qué monstruo marino de la creación se menciona en Job?", opciones: ["El Leviatán", "El Minotauro", "El Centauro", "El Kraken"], correcta: 0 },
            { pregunta: "¿Qué bestia terrestre poderosa se describe en el libro de Job?", opciones: ["El Behemot", "El Mamut", "El Dinosauro", "El Dragón"], correcta: 0 },
            { pregunta: "¿Qué vestimenta natural usaron Adán y Eva primeramente?", opciones: ["Hojas de higuera", "Pieles de cocodrilo", "Telas de lino", "Lana de oveja"], correcta: 0 },
            { pregunta: "¿Qué separa el agricultor del trigo en la cosecha bíblica?", opciones: ["La paja", "Las flores", "El tallo", "La raíz"], correcta: 0 },
            { pregunta: "¿Qué animal es símbolo de agilidad en los montes en los Salmos?", opciones: ["La cierva", "La vaca", "El cerdo", "El oso"], correcta: 0 },
            { pregunta: "¿Por qué no debemos dejar goteando los grifos en casa?", opciones: ["Evita el desperdicio inútil de litros de agua potable", "Para que no suene", "Porque se oxida", "No afecta"], correcta: 0 },
            { pregunta: "¿Qué ave nocturna habitaba en lugares desolados según Isaías?", opciones: ["El búho / lechuza", "El colibrí", "El canario", "El flamenco"], correcta: 0 },
            { pregunta: "¿Qué nos enseñan las cuatro estaciones del año?", opciones: ["El orden perfecto de los tiempos creados por Dios", "Que el clima es loco", "Que no hay control", "Nada"], correcta: 0 },
            { pregunta: "¿Qué debemos hacer con la chatarra electrónica vieja?", opciones: ["Llevarla a puntos limpios de reciclaje e-waste", "Lanzarla a los ríos", "Quemar sus componentes", "Tirarla a la calle"], correcta: 0 },
            { pregunta: "¿Qué cultivo principal de grano alimentaba al antiguo Israel?", opciones: ["El trigo y la cebada", "El arroz", "El maíz", "La soya"], correcta: 0 },
            { pregunta: "¿Qué nos enseña el firmamento estrellado según el Salmo 19?", opciones: ["Cuenta la gloria de Dios y las obras de sus manos", "Que el espacio está vacío", "Que no hay diseño", "Que el Sol es frío"], correcta: 0 },
            { pregunta: "¿Qué animal utilizó Jesús para su entrada triunfal a Jerusalén?", opciones: ["Un pollino / asno", "Un caballo de guerra", "Un camello", "Un elefante"], correcta: 0 },
            { pregunta: "¿Qué rol tienen los jóvenes de Generación Oasis en la sociedad?", opciones: ["Ser guardianes del medio ambiente y testimonio de fe", "Estar en el celular todo el día", "Ignorar a los demás", "Contaminar"], correcta: 0 },
            { pregunta: "¿Qué dulce natural es más dulce que la miel según los Salmos?", opciones: ["Los juicios y la palabra de Dios", "El azúcar", "El sirope", "El fruto del cactus"], correcta: 0 },
            { pregunta: "¿Qué sustancia no debe ser arrojada al alcantarillado?", opciones: ["Aceite de cocina, plásticos y químicos", "Agua de lluvia", "Hojas secas", "Agua limpia"], correcta: 0 },
            { pregunta: "¿Qué aves polinizan flores además de las abejas?", opciones: ["Los colibríes", "Los buitres", "Los pelícanos", "Los pingüinos"], correcta: 0 },
            { pregunta: "¿Qué significa amar la Creación?", opciones: ["Respetar la vida animal, vegetal y los recursos de Dios", "Comprar cosas sin parar", "Destruir árboles", "Tirar basura"], correcta: 0 },
            { pregunta: "¿Qué animal veloz usa la metáfora bíblica para correr sin cansarse?", opciones: ["El águila al levantar alas", "El caracol", "La tortuga", "El perezoso"], correcta: 0 },
            { pregunta: "¿Quién dijo: 'Yo soy la vid verdadera, y mi Padre es el labrador'?", opciones: ["Jesús", "Pedro", "Pablo", "Moisés"], correcta: 0 },
            { pregunta: "¿Qué medio de transporte ecológico no emite gases contaminantes?", opciones: ["La bicicleta / Caminar", "El auto de gasolina", "La motocicleta", "El avión"], correcta: 0 },
            { pregunta: "¿Qué pigmento le da el color verde a las plantas?", opciones: ["Clorofila", "Caroteno", "Oxígeno", "Calcio"], correcta: 0 },
            { pregunta: "¿Por qué se deben proteger las especies silvestres en peligro de extinción?", opciones: ["Para mantener la biodiversidad y el equilibrio del planeta", "Por capricho", "No se deben proteger", "Para cazarlas"], correcta: 0 },
            { pregunta: "¿Qué actividad ecológica fomenta el grupo juvenil Generación Oasis?", opciones: ["Jornadas de siembra, recolección de basura y limpieza", "Quemarle las hojas a los árboles", "Usar botellas desechables", "Desperdiciar papel"], correcta: 0 },
            { pregunta: "¿Qué sopló Dios en el ser humano para darle vida?", opciones: ["Aliento de vida", "Fuego", "Viento fuerte", "Polvo de estrellas"], correcta: 0 },
            { pregunta: "¿Qué lección nos deja la naturaleza cada primavera o época de lluvia?", opciones: ["La vida siempre se renueva con la gracia de Dios", "Que todo muere", "Que no hay esperanza", "Ninguna"], correcta: 0 },
            { pregunta: "¿A quién pertenece la Tierra y su plenitud según el Salmo 24?", opciones: ["A Jehová Dios", "A los gobernantes", "A las empresas", "A nadie"], correcta: 0 },
            { pregunta: "¿Qué esperanza nos da la promesa de un cielo nuevo y una tierra nueva?", opciones: ["Una creación restaurada en paz y justicia divina", "El fin de todo", "La destrucción eterna", "Nada"], correcta: 0 },
            { pregunta: "¿Quién es el Creador de los cielos, la tierra y el mar?", opciones: ["Dios Altísimo", "La casualidad", "La naturaleza sola", "El ser humano"], correcta: 0 }
        ]
    },
    "jesus": {
        titulo: "✝️ Jesús y sus Enseñanzas",
        preguntas: [
            { pregunta: "¿Dónde nació Jesús?", opciones: ["Belén", "Nazaret", "Jerusalén", "Cafarnaúm"], correcta: 0 },
            { pregunta: "¿En qué ciudad creció Jesús durante su infancia?", opciones: ["Nazaret", "Belén", "Jericó", "Damasco"], correcta: 0 },
            { pregunta: "¿Quién fue la madre terrenal de Jesús?", opciones: ["María", "Marta", "Isabel", "Salomé"], correcta: 0 },
            { pregunta: "¿Quién fue el padre terrenal y adoptivo de Jesús?", opciones: ["José", "Zacarías", "Joaquín", "Simeón"], correcta: 0 },
            { pregunta: "¿Cuál era la profesión de José, el padre terrenal de Jesús?", opciones: ["Carpintero", "Pescador", "Sacerdote", "Pastor"], correcta: 0 },
            { pregunta: "¿En qué río fue bautizado Jesús?", opciones: ["Jordán", "Nilo", "Éufrates", "Tigris"], correcta: 0 },
            { pregunta: "¿Quién bautizó a Jesús en el río Jordán?", opciones: ["Juan el Bautista", "Pedro", "Santiago", "Aarón"], correcta: 0 },
            { pregunta: "¿En qué forma descendió el Espíritu Santo sobre Jesús en su bautismo?", opciones: ["Como una paloma", "Como una llama", "Como una nube", "Como un rayo"], correcta: 0 },
            { pregunta: "¿Cuántos días ayunó Jesús en el desierto antes de iniciar su ministerio?", opciones: ["40 días", "30 días", "7 días", "12 días"], correcta: 0 },
            { pregunta: "¿Quién tentó a Jesús en el desierto?", opciones: ["El diablo / Satanás", "Herodes", "Los fariseos", "Pilato"], correcta: 0 },
            { pregunta: "¿Cuántos apóstoles principales eligió Jesús?", opciones: ["12", "10", "7", "70"], correcta: 0 },
            { pregunta: "¿Cuál fue el primer milagro de Jesús registrado en el Evangelio de Juan?", opciones: ["Convertir el agua en vino en las bodas de Caná", "Caminar sobre el agua", "Multiplicar los panes", "Sanar al ciego"], correcta: 0 },
            { pregunta: "¿A qué se dedicaban Pedro, Andrés, Santiago y Juan antes de seguir a Jesús?", opciones: ["Pescadores", "Recaudadores de impuestos", "Carpinteros", "Soldados"], correcta: 0 },
            { pregunta: "¿Qué famoso sermón pronunció Jesús enseño las Bienaventuranzas?", opciones: ["El Sermón del Monte", "El Sermón del Templo", "El Sermón del Valle", "El Sermón de Getsemaní"], correcta: 0 },
            { pregunta: "¿Cómo enseñó Jesús a orar a sus discípulos?", opciones: ["Con la oración del Padre Nuestro", "Con el Salmo 23", "Con la oración de Jabes", "En silencio absoluto"], correcta: 0 },
            { pregunta: "¿Qué significa la palabra 'Jesús'?", opciones: ["El Señor Salva / Salvador", "Dios es rey", "El enviado de paz", "El maestro insigne"], correcta: 0 },
            { pregunta: "¿Qué significa el título 'Cristo' o 'Mesías'?", opciones: ["El Ungido", "El Rey del templo", "El Profeta divino", "El Gobernante"], correcta: 0 },
            { pregunta: "¿Qué milagro hizo Jesús para alimentar a más de 5,000 personas?", opciones: ["Multiplicó 5 panes y 2 peces", "Hizo llover maná", "Brotó pan de las rocas", "Multiplicó fruta"], correcta: 0 },
            { pregunta: "¿Cómo calmó Jesús la gran tempestad en el mar de Galilea?", opciones: ["Reprendió al viento y al mar diciendo: ¡Calla, enmudece!", "Oró 3 días", "Remó más fuerte", "Sopló sobre las olas"], correcta: 0 },
            { pregunta: "¿Quién caminó sobre el agua hacia Jesús pero comenzó a hundirse por dudar?", opciones: ["Pedro", "Juan", "Tomás", "Felipe"], correcta: 0 },
            { pregunta: "¿A qué amigo resucitó Jesús en Betania tras 4 días en la tumba?", opciones: ["Lázaro", "Esteban", "Simón", "Nicodemo"], correcta: 0 },
            { pregunta: "¿Cómo se llamaban las hermanas de Lázaro?", opciones: ["Marta y María", "Sara y Rebeca", "Raquel y Lea", "Ester y Rut"], correcta: 0 },
            { pregunta: "¿Qué cobrador de impuestos de pequeña estatura se subió a un sicómoro para ver a Jesús?", opciones: ["Zaqueo", "Mateo", "Cornelio", "Caifás"], correcta: 0 },
            { pregunta: "¿Qué parábola enseñó Jesús sobre la misericordia hacia un hombre herido en el camino?", opciones: ["El Buen Samaritano", "El Hijo Pródigo", "El Sembrador", "La Oveja Perdida"], correcta: 0 },
            { pregunta: "¿Qué parábola muestra el amor de un padre que perdona a su hijo arrepentido?", opciones: ["El Hijo Pródigo", "Los Diez Talentos", "La Gran Cena", "El Trigo y la Cizaña"], correcta: 0 },
            { pregunta: "¿Qué parábola relata a un pastor que deja 99 ovejas para buscar a una?", opciones: ["La Oveja Perdida", "La Moneda Perdida", "El Buen Pastor", "La Red de Pesca"], correcta: 0 },
            { pregunta: "¿Qué parábola enseña sobre cómo la Palabra de Dios cae en diferentes corazones?", opciones: ["El Sembrador", "La Levadura", "La Perla de Gran Precio", "El Grano de Mostaza"], correcta: 0 },
            { pregunta: "¿Qué mandamiento dijo Jesús que es el más grande de todos?", opciones: ["Amarás al Señor tu Dios con todo tu corazón, alma y mente", "No matarás", "Guardarás el día de reposo", "Darás el diezmo"], correcta: 0 },
            { pregunta: "¿Cuál es el segundo mandamiento semejante al primero según Jesús?", opciones: ["Amarás a tu prójimo como a ti mismo", "No hurtarás", "Honrarás a tu padre", "No dirás mentiras"], correcta: 0 },
            { pregunta: "¿Con qué frase identificó Jesús su relación con las ovejas?", opciones: ["Yo soy el Buen Pastor", "Yo soy el gran rey", "Yo soy el guardián", "Yo soy la luz del templo"], correcta: 0 },
            { pregunta: "¿Con qué frase definió Jesús el camino al Padre Dios?", opciones: ["Yo soy el camino, la verdad y la vida", "Yo soy la puerta del templo", "Yo soy el profeta", "Yo soy el juez"], correcta: 0 },
            { pregunta: "¿Quién traicionó a Jesús por 30 piezas de plata?", opciones: ["Judas Iscariote", "Pedro", "Tomás", "Ananías"], correcta: 0 },
            { pregunta: "¿En qué lugar celebró Jesús la Última Cena con sus apóstoles?", opciones: ["En el Aposento Alto / Cenáculo", "En el Templo de Jerusalén", "En la casa de Pilato", "En Betania"], correcta: 0 },
            { pregunta: "¿Qué elementos usó Jesús en la Última Cena como símbolo de su cuerpo y sangre?", opciones: ["El pan y el vino", "El agua y las frutas", "El trigo y el aceite", "El cordero y las hierbas"], correcta: 0 },
            { pregunta: "¿En qué huerto fue a orar Jesús antes de ser arrestado?", opciones: ["Getsemaní", "Edén", "Siloé", "Monte Carmelo"], correcta: 0 },
            { pregunta: "¿Qué apóstol cortó la oreja del siervo del sumo sacerdote y fue reprendido por Jesús?", opciones: ["Pedro", "Juan", "Santiago", "Andrés"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba el siervo a quien Jesús le sanó la oreja en Getsemaní?", opciones: ["Malco", "Anás", "Caifás", "Barrabás"], correcta: 0 },
            { pregunta: "¿Quién era el Sumo Sacerdote que juzgó a Jesús esa noche?", opciones: ["Caifás", "Pilato", "Herodes", "Ananías"], correcta: 0 },
            { pregunta: "¿Qué preso fue liberado por la multitud en lugar de Jesús?", opciones: ["Barrabás", "Dimas", "Gestas", "Silas"], correcta: 0 },
            { pregunta: "¿Quién era el gobernador romano que lavó sus manos al condenar a Jesús?", opciones: ["Poncio Pilato", "César Augusto", "Tiberio", "Félix"], correcta: 0 },
            { pregunta: "¿Qué corona le pusieron los soldados a Jesús para burlarse de él?", opciones: ["Una corona de espinas", "Una corona de oro", "Una corona de laurel", "Una corona de plata"], correcta: 0 },
            { pregunta: "¿En qué lugar o monte fue crucificado Jesús?", opciones: ["Gólgota / Calvario", "Monte Sinaí", "Monte de los Olivos", "Monte Tabor"], correcta: 0 },
            { pregunta: "¿Qué inscripción pusieron sobre la cruz de Jesús?", opciones: ["INRI (Jesús Nazareno, Rey de los Judíos)", "El Profeta de Galilea", "El Hombre Justo", "El Rey de Roma"], correcta: 0 },
            { pregunta: "¿Qué dijo Jesús en la cruz sobre quienes lo crucificaban?", opciones: ["Padre, perdónalos, porque no saben lo que hacen", "Que caiga fuego sobre ellos", "Dios mío castígalos", "No hay perdón"], correcta: 0 },
            { pregunta: "¿A qué hora aproximada murió Jesús en la cruz según las Escrituras?", opciones: ["A la hora novena (3:00 p.m.)", "A la medianoche", "Al amanecer", "A la hora sexta"], correcta: 0 },
            { pregunta: "¿Quién cedió su sepulcro nuevo para enterrar el cuerpo de Jesús?", opciones: ["José de Arimatea", "Nicodemo", "Simón de Cirene", "Lázaro"], correcta: 0 },
            { pregunta: "¿Qué fariseo principal ayudó a enterrar a Jesús trayendo especias aromáticas?", opciones: ["Nicodemo", "Gamaliel", "Saulo", "Caifás"], correcta: 0 },
            { pregunta: "¿En qué día de la semana resucitó Jesús de entre los muertos?", opciones: ["El primer día de la semana (Domingo)", "El sábado", "El viernes", "El tercer mes"], correcta: 0 },
            { pregunta: "¿A qué mujer se le apareció primero Jesús resucitado cerca del sepulcro?", opciones: ["María Magdalena", "Marta", "Salomé", "Juana"], correcta: 0 },
            { pregunta: "¿Qué apóstol dijo que no creería en la resurrección hasta meter su dedo en las heridas?", opciones: ["Tomás", "Felipe", "Bartolomé", "Tadeo"], correcta: 0 },
            { pregunta: "¿En qué camino se apareció Jesús resucitado a dos discípulos que no lo reconocían?", opciones: ["Camino a Emaús", "Camino a Damasco", "Camino a Jericó", "Camino a Gaza"], correcta: 0 },
            { pregunta: "¿Qué pregunta le hizo Jesús tres veces a Pedro a orillas del mar tras resucitar?", opciones: ["Simón, ¿me amas?", "Simón, ¿por qué dudaste?", "¿Vas a pescar más?", "¿Dónde están los otros?"], correcta: 0 },
            { pregunta: "¿Cuántos días permaneció Jesús en la tierra enseñando tras su resurrección?", opciones: ["40 días", "50 días", "7 días", "100 días"], correcta: 0 },
            { pregunta: "¿Desde qué monte ascendió Jesús al cielo ante la vista de sus discípulos?", opciones: ["Monte de los Olivos", "Monte Sinaí", "Monte Carmelo", "Monte Hermón"], correcta: 0 },
            { pregunta: "¿Qué gran comisión les dejó Jesús a sus discípulos antes de ascender?", opciones: ["Id y haced discípulos a todas las naciones", "Quédense en Jerusalén para siempre", "Construyan un gran templo", "Escriban libros solares"], correcta: 0 },
            { pregunta: "¿Qué prometió Jesús enviar a sus discípulos tras su ascensión?", opciones: ["El Consolador / El Espíritu Santo", "Un ejército terrenal", "Riquezas materiales", "Un nuevo rey romano"], correcta: 0 },
            { pregunta: "¿Qué milagro hizo Jesús con el hijo de la viuda de Naín?", opciones: ["Lo resucitó mientras lo llevaban a enterrar", "Lo sanó de ceguera", "Lo multiplicó", "Lo libró de prisión"], correcta: 0 },
            { pregunta: "¿A qué mujer sanó Jesús al tocar ella su manto con fe?", opciones: ["A la mujer con el flujo de sangre de 12 años", "A la reina de Saba", "A la esposa de Pilato", "A la hermana de Moisés"], correcta: 0 },
            { pregunta: "¿Qué le dijo Jesús a la mujer sanada por tocar su manto?", opciones: ["Tu fe te ha salvado, ve en paz", "No vuelvas a salir", "Busca al sacerdote", "Trae una ofrenda grande"], correcta: 0 },
            { pregunta: "¿Qué le dijo Jesús al paralítico de Capernaúm antes de sanarlo?", opciones: ["Tus pecados te son perdonados... Levántate y anda", "Paga tu diezmo", "Busca ayuda en el mar", "Espera al ángel"], correcta: 0 },
            { pregunta: "¿Qué le dijo Jesús a la mujer sorprendida en adulterio frente a los acusadores?", opciones: ["El que esté libre de pecado, tire la primera piedra", "Llévenla al templo", "Condénenla de inmediato", "No me molesten"], correcta: 0 },
            { pregunta: "¿Qué le dijo Jesús a la mujer adúltera cuando todos se retiraron?", opciones: ["Ni yo te condeno; vete y no peques más", "Paga una fianza", "Ve a esconderte", "Busca a los jueces"], correcta: 0 },
            { pregunta: "¿Qué milagro hizo Jesús en la hija de Jairo?", opciones: ["La resucitó diciéndole: Talita cumi", "Le devolvió la vista", "Le curó la lepra", "La hizo hablar"], correcta: 0 },
            { pregunta: "¿Qué significa la frase 'Talita cumi' pronunciada por Jesús?", opciones: ["Niña, a ti te digo, levántate", "Dios te bendiga", "Despierta del sueño", "Sé limpia"], correcta: 0 },
            { pregunta: "¿Cuántos leprosos sanó Jesús en el camino, de los cuales solo uno regresó a dar gracias?", opciones: ["10 leprosos", "12 leprosos", "5 leprosos", "7 leprosos"], correcta: 0 },
            { pregunta: "¿De qué nacionalidad era el único leproso agradecido que volvió a alabar a Dios?", opciones: ["Samaritano", "Judío", "Romano", "Griego"], correcta: 0 },
            { pregunta: "¿Qué dijo Jesús sobre los niños cuando los discípulos intentaban alejarlos?", opciones: ["Dejad a los niños venir a mí, porque de los tales es el reino de los cielos", "Llévenselos a sus casas", "No interrumpan mi clase", "Los niños no entienden"], correcta: 0 },
            { pregunta: "¿Qué le respondió Jesús al joven rico que le preguntó qué hacer para tener la vida eterna?", opciones: ["Vende lo que tienes, dáselo a los pobres y sígueme", "Construye un templo", "Hazte rey", "Ayuna tres meses"], correcta: 0 },
            { pregunta: "¿Qué animal usó Jesús en un dicho para ilustrar lo difícil que es para un rico entrar al reino?", opciones: ["Un camello pasando por el ojo de una aguja", "Un elefante cruzando una puerta", "Un caballo corriendo", "Un león en una jaula"], correcta: 0 },
            { pregunta: "¿Qué hizo Jesús al ver a los vendedores y mercaderes en el Templo de Jerusalén?", opciones: ["Volcó las mesas y los echó diciendo: Mi casa será llamada casa de oración", "Les compró palomas", "Predicó con ellos", "Los nombró sacerdotes"], correcta: 0 },
            { pregunta: "¿Qué apóstol es conocido por ser el 'discípulo amado'?", opciones: ["Juan", "Pedro", "Santiago", "Andrés"], correcta: 0 },
            { pregunta: "¿Qué apóstol era hermano de Pedro y lo llevó a conocer a Jesús?", opciones: ["Andrés", "Felipe", "Bartolomé", "Mateo"], correcta: 0 },
            { pregunta: "¿Qué dijo Jesús sobre el amor a los enemigos?", opciones: ["Amad a vuestros enemigos y bendecid a los que os maldicen", "Aborrecedlos", "Ignórenlos", "Pidan venganza"], correcta: 0 },
            { pregunta: "¿Qué metáfora usó Jesús para describir a sus seguidores en el mundo?", opciones: ["Vosotros sois la sal de la tierra y la luz del mundo", "Vosotros sois los reyes", "Vosotros sois el oro", "Vosotros sois los jueces"], correcta: 0 },
            { pregunta: "¿Qué les dijo Jesús a sus discípulos sobre la preocupación por el alimento y el vestido?", opciones: ["Buscad primeramente el reino de Dios y su justicia, y todo será añadido", "Trabajen sin descansar", "Acumulen riquezas", "Pidan al gobierno"], correcta: 0 },
            { pregunta: "¿Qué milagro hizo Jesús en el estanque de Betesda?", opciones: ["Sanó a un hombre que llevaba 38 años enfermo", "Convirtió el agua en aceite", "Hizo flotar una hacha", "Limpió a 100 leprosos"], correcta: 0 },
            { pregunta: "¿Qué hizo Jesús con el ciego de nacimiento para devolverle la vista?", opciones: ["Hizo barro con saliva, lo puso en sus ojos y le mandó a lavarse en Siloé", "Tocó una campanilla", "Le dio de beber vino", "Sopló tres veces"], correcta: 0 },
            { pregunta: "¿Qué frase pronunció Jesús en la cruz al exhalar su último suspiro?", opciones: ["Consumado es / En tus manos encomiendo mi espíritu", "He perdido", "Mañana volveré", "Ayúdenme"], correcta: 0 },
            { pregunta: "¿Quién reconoció al morir Jesús diciendo: Verdaderamente este hombre era Hijo de Dios?", opciones: ["El centurión romano", "Poncio Pilato", "Herodes", "Caifás"], correcta: 0 },
            { pregunta: "¿Qué apóstol sustituyó a Judas Iscariote tras la ascensión de Jesús?", opciones: ["Matías", "Pablo", "Bárnabas", "Silas"], correcta: 0 },
            { pregunta: "¿Qué apóstol persiguió primero a los cristianos pero tuvo un encuentro con Jesús camino a Damasco?", opciones: ["Saulo / Pablo", "Esteban", "Apolo", "Timoteo"], correcta: 0 },
            { pregunta: "¿Qué vio Saulo en el camino a Damasco que lo dejó ciego por 3 días?", opciones: ["Una luz resplandeciente del cielo y la voz de Jesús", "Un relámpago común", "Un ángel con espada", "Una tormenta de arena"], correcta: 0 },
            { pregunta: "¿Quién oró por Saulo en Damasco para que recuperara la vista?", opciones: ["Ananías", "Pedro", "Juan", "Felipe"], correcta: 0 },
            { pregunta: "¿Qué nombre adoptó Saulo tras convertirse en apóstol de Jesús?", opciones: ["Pablo", "Pedro", "Santiago", "Silvano"], correcta: 0 },
            { pregunta: "¿Qué dijo Jesús sobre el juzgar a los demás?", opciones: ["No juzguéis, para que no seáis juzgados", "Juzguen a todos", "Corrijan a la fuerza", "Condenen al malvado"], correcta: 0 },
            { pregunta: "¿Qué analogía usó Jesús sobre la viga y la paja en la enseñanza?", opciones: ["Saca primero la viga de tu ojo para ver la paja en el ajeno", "Busca paja en el granero", "Construye una casa de vigas", "Limpia la madera"], correcta: 0 },
            { pregunta: "¿Qué es la 'Regla de Oro' enseñada por Jesús?", opciones: ["Haz con los demás lo que quieras que hagan contigo", "El oro vale más que la plata", "Gana siempre", "Defiéndete con fuerza"], correcta: 0 },
            { pregunta: "¿Sobre qué fundamento dijo Jesús que edifica su casa el hombre sabio?", opciones: ["Sobre la roca (sus palabras)", "Sobre la arena", "Sobre el barro", "Sobre la madera"], correcta: 0 },
            { pregunta: "¿Qué le ocurre a la casa edificada sobre la arena cuando llegan los ríos y vientos?", opciones: ["Cae y su ruina es grande", "Permanecerá firme", "Se mueve un poco", "Se convierte en piedra"], correcta: 0 },
            { pregunta: "¿Quién era la mujer samaritana que habló con Jesús junto al pozo de Jacob?", opciones: ["Una mujer que buscaba agua y a quien Jesús ofreció agua de vida", "Una reina de Samaria", "La esposa de Herodes", "Una discípula de Juan"], correcta: 0 },
            { pregunta: "¿Qué le ofreció Jesús a la mujer samaritana en el pozo?", opciones: ["El agua viva que salta para vida eterna", "Oro y plata", "Una casa en Jerusalén", "Comida del templo"], correcta: 0 },
            { pregunta: "¿A qué hora descendió oscuridad sobre la tierra durante la crucifixión de Jesús?", opciones: ["Desde la hora sexta hasta la novena (12:00 p.m. a 3:00 p.m.)", "A medianoche", "Al amanecer", "Toda la noche"], correcta: 0 },
            { pregunta: "¿Qué le ocurrió al velo del Templo cuando Jesús murió?", opciones: ["Se rasgó en dos, de arriba abajo", "Se quemó", "Se cayó al suelo", "Se llenó de agua"], correcta: 0 },
            { pregunta: "¿Qué acontecimiento sísmico ocurrió inmediatamente tras la muerte de Jesús?", opciones: ["Un gran terremoto y las rocas se hendieron", "Un tsunami", "Una erupción volcánica", "Un gran huracán"], correcta: 0 },
            { pregunta: "¿Qué apóstol corrió junto con Juan hacia el sepulcro al oír que estaba vacío?", opciones: ["Pedro", "Tomás", "Mateo", "Santiago"], correcta: 0 },
            { pregunta: "¿Qué dijo Jesús sobre tomar la cruz cada día?", opciones: ["Si alguno quiere venir en pos de mí, niéguese a sí mismo, tome su cruz y sígame", "Lleve una cruz de madera colgada", "Evite las pruebas", "Compre una cruz de oro"], correcta: 0 },
            { pregunta: "¿A quién resucitó Jesús diciendo: 'Joven, a ti te digo, levántate'?", opciones: ["Al hijo de la viuda de Naín", "A Lázaro", "A la hija de Jairo", "Al siervo del centurión"], correcta: 0 },
            { pregunta: "¿Cómo demostró Jesús la actitud de servicio a sus apóstoles en la Última Cena?", opciones: ["Lavándoles los pies", "Sirviendo la comida", "Regalándoles túnicas", "Coronándolos"], correcta: 0 },
            { pregunta: "¿Qué mandato nuevo les dio Jesús a sus apóstoles esa noche?", opciones: ["Que os améis unos a otros como yo os he amado", "Que no salgan de Jerusalén", "Que construyan iglesias", "Que guarden silencio"], correcta: 0 },
            { pregunta: "¿Quién vive e intercede por nosotros hoy según la fe cristiana?", opciones: ["Jesucristo resucitado a la diestra de Dios", "Los antiguos profetas", "Los reyes del pasado", "Nadie"], correcta: 0 }
        ]
    },
    "nuevo_testamento": {
        titulo: "📜 Nuevo Testamento",
        preguntas: [
            { pregunta: "¿Cuántos libros componen el Nuevo Testamento?", opciones: ["27 libros", "39 libros", "66 libros", "12 libros"], correcta: 0 },
            { pregunta: "¿Cuáles son los cuatro Evangelios del Nuevo Testamento?", opciones: ["Mateo, Marcos, Lucas y Juan", "Génesis, Éxodo, Levitico y Números", "Pedro, Pablo, Santiago y Judas", "Hechos, Romanos, Corintios y Gálatas"], correcta: 0 },
            { pregunta: "¿Qué libro del Nuevo Testamento narra la historia del nacimiento y expansión de la iglesia primitiva?", opciones: ["Hechos de los Apóstoles", "Apocalipsis", "Romanos", "Hebreos"], correcta: 0 },
            { pregunta: "¿Quién escribió el libro de los Hechos de los Apóstoles?", opciones: ["Lucas", "Pablo", "Pedro", "Juan"], correcta: 0 },
            { pregunta: "¿Qué evento marcó el inicio de la predicación de la Iglesia con el Espíritu Santo?", opciones: ["El día de Pentecostés", "La Pascua", "La fiesta de los tabernáculos", "El día de reposo"], correcta: 0 },
            { pregunta: "¿En qué forma se manifestó el Espíritu Santo sobre los discípulos en Pentecostés?", opciones: ["Como lenguas repartidas de fuego y un viento recio", "Como una nube de agua", "Como una luz dorada", "Como un terremoto suave"], correcta: 0 },
            { pregunta: "¿Quién predicó el primer gran discurso en Pentecostés convirtiendo a 3,000 personas?", opciones: ["Pedro", "Pablo", "Esteban", "Felipe"], correcta: 0 },
            { pregunta: "¿Quién fue el primer mártir de la iglesia cristiana apedreado por su fe?", opciones: ["Esteban", "Santiago", "Felipe", "Antipas"], correcta: 0 },
            { pregunta: "¿Qué joven guardaba las ropas de los que apedreaban a Esteban?", opciones: ["Saulo (Pablo)", "Timoteo", "Tito", "Marcos"], correcta: 0 },
            { pregunta: "¿Quién llevó el evangelio a Samaria y luego bautizó al etíope eunuco?", opciones: ["Felipe el evangelista", "Pedro", "Tomás", "Bárnabas"], correcta: 0 },
            { pregunta: "¿Qué leía el etíope eunuco en su carro cuando Felipe se le acercó?", opciones: ["El libro del profeta Isaías", "El libro de Génesis", "Los Salmos", "El libro de Daniel"], correcta: 0 },
            { pregunta: "¿En qué ciudad se les llamó 'cristianos' por primera vez a los discípulos?", opciones: ["Antioquía", "Jerusalén", "Roma", "Éfeso"], correcta: 0 },
            { pregunta: "¿Quién acompañó a Pablo en su primer viaje misionero?", opciones: ["Bernabé", "Silas", "Timoteo", "Tito"], correcta: 0 },
            { pregunta: "¿Qué apóstol tuvo una visión de una gran sábana con animales limpios e inmundos?", opciones: ["Pedro", "Pablo", "Juan", "Santiago"], correcta: 0 },
            { pregunta: "¿A qué centurión romano envió Dios a Pedro para predicarle a los gentiles?", opciones: ["Cornelio", "Julio", "Félix", "Lisio"], correcta: 0 },
            { pregunta: "¿Qué rey mandó matar a espada a Santiago, hermano de Juan?", opciones: ["Herodes Agripa I", "Herodes el Grande", "César Nerón", "Pilato"], correcta: 0 },
            { pregunta: "¿Cómo escapó Pedro de la cárcel cuando estaba encadenado entre dos soldados?", opciones: ["Un ángel del Señor le abrió las puertas y le soltó las cadenas", "Los guardias se durmieron ebrios", "Hizo un túnel", "Bernabé pagó la fianza"], correcta: 0 },
            { pregunta: "¿A qué casa fue Pedro tras ser liberado por el ángel de la prisión?", opciones: ["A la casa de María, madre de Juan Marcos", "A la casa de Lidia", "Al templo", "A la casa de Priscila"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba la sirvienta que escuchó la voz de Pedro en la puerta y corrió a avisar sin abrir?", opciones: ["Rode", "Febe", "Priscila", "Lidia"], correcta: 0 },
            { pregunta: "¿Cuál es la epístola o carta más larga escrita por el apóstol Pablo?", opciones: ["Romanos", "1 Corintios", "Gálatas", "Efesios"], correcta: 0 },
            { pregunta: "¿En qué carta escribe Pablo el famoso capítulo sobre el Amor (1 Corintios 13)?", opciones: ["1 Corintios", "Romanos", "Filipenses", "Colosenses"], correcta: 0 },
            { pregunta: "¿Cuáles son las tres virtudes teologales mencionadas al final de 1 Corintios 13?", opciones: ["La fe, la esperanza y el amor", "La paz, el gozo y la paciencia", "La sabiduría, la fuerza y la fe", "La gracia, la verdad y la luz"], correcta: 0 },
            { pregunta: "¿Qué epístola habla detalladamente de la Armadura de Dios?", opciones: ["Efesios (Capítulo 6)", "Gálatas", "Filipenses", "Tito"], correcta: 0 },
            { pregunta: "¿Cuáles son partes de la Armadura de Dios en Efesios 6?", opciones: ["El yelmo de la salvación, el escudo de la fe y la espada del Espíritu", "La lanza de la verdad", "El arco de victoria", "La capa de sabiduría"], correcta: 0 },
            { pregunta: "¿Qué es la 'Espada del Espíritu' según Efesios 6?", opciones: ["La Palabra de Dios", "La oración constante", "La fe", "La verdad"], correcta: 0 },
            { pregunta: "¿En qué carta Pablo expresa: 'Para mí el vivir es Cristo, y el morir es ganancia'?", opciones: ["Filipenses", "Gálatas", "2 Corintios", "Filemón"], correcta: 0 },
            { pregunta: "¿A qué joven pastor le escribió Pablo dos cartas pastorales dándole instrucciones para la iglesia?", opciones: ["Timoteo", "Tito", "Apolo", "Clemente"], correcta: 0 },
            { pregunta: "¿Qué frase le escribió Pablo a Timoteo sobre su juventud?", opciones: ["Ninguno tenga en poco tu juventud, sino sé ejemplo de los creyentes", "Espera a ser mayor para enseñar", "No hables en público", "Busca riquezas primero"], correcta: 0 },
            { pregunta: "¿Qué vendedor de púrpura de la ciudad de Tiatira se convirtió al oír a Pablo en Filipos?", opciones: ["Lidia", "Priscila", "Febe", "Damaris"], correcta: 0 },
            { pregunta: "¿Qué ocurrió en la cárcel de Filipos mientras Pablo y Silas cantaban himnos a medianoche?", opciones: ["Un gran terremoto abrió las puertas y soltó las cadenas", "Los guardias los liberaron", "Llovió dentro de la celda", "Apareció una luz sin ruido"], correcta: 0 },
            { pregunta: "¿Qué preguntó el carcelero de Filipos a Pablo y Silas tras el terremoto?", opciones: ["Señores, ¿qué debo hacer para ser salvo?", "¿Por qué destruyeron la cárcel?", "¿A dónde van a huir?", "¿Quiénes son ustedes?"], correcta: 0 },
            { pregunta: "¿Qué le respondieron Pablo y Silas al carcelero de Filipos?", opciones: ["Cree en el Señor Jesucristo, y serás salvo, tú y tu casa", "Paga los daños de la celda", "Corre antes que vengan los soldados", "Pide perdón a Roma"], correcta: 0 },
            { pregunta: "¿En qué famosa ciudad griega predicó Pablo en el Areópago sobre el 'Dios No Conocido'?", opciones: ["Atenas", "Corinto", "Esparta", "Salónica"], correcta: 0 },
            { pregunta: "¿Qué oficio compartían Aquila y Priscila con el apóstol Pablo?", opciones: ["Hacedores de tiendas / carpas", "Pescadores", "Orfebres", "Escribas"], correcta: 0 },
            { pregunta: "¿Qué predicador elocuente de Alejandría fue instruido por Priscila y Aquila?", opciones: ["Apolo", "Esteban", "Gayo", "Epafras"], correcta: 0 },
            { pregunta: "¿Quién fue el autor de la carta de Santiago?", opciones: ["Santiago (hermano del Señor / líder en Jerusalén)", "Santiago hijo de Zebedeo", "Santiago el menor", "Santiago de Alfeo"], correcta: 0 },
            { pregunta: "¿Qué enseña la carta de Santiago respecto a la fe sin obras?", opciones: ["La fe sin obras está muerta", "La fe sola es suficiente sin importar el acto", "Las obras no valen nada", "La fe es secundaria"], correcta: 0 },
            { pregunta: "¿Qué miembro pequeño del cuerpo compara Santiago con el freno del caballo y el timón del barco?", opciones: ["La lengua", "La mano", "El ojo", "El pie"], correcta: 0 },
            { pregunta: "¿Cuántas cartas en el Nuevo Testamento llevan el nombre del apóstol Pedro?", opciones: ["2 cartas (1 y 2 Pedro)", "1 carta", "3 cartas", "5 cartas"], correcta: 0 },
            { pregunta: "¿Cuántas cartas en el Nuevo Testamento llevan el nombre del apóstol Juan?", opciones: ["3 cartas (1, 2 y 3 Juan)", "1 carta", "2 cartas", "4 cartas"], correcta: 0 },
            { pregunta: "¿Quién escribió el libro de Apocalipsis?", opciones: ["El apóstol Juan", "Pablo", "Pedro", "Daniel"], correcta: 0 },
            { pregunta: "¿En qué isla estaba Juan cuando recibió las visiones de Apocalipsis?", opciones: ["Isla de Patmos", "Isla de Creta", "Isla de Chipre", "Isla de Malta"], correcta: 0 },
            { pregunta: "¿A cuántas iglesias de Asia Menor van dirigidas las cartas iniciales en Apocalipsis?", opciones: ["7 iglesias", "12 iglesias", "5 iglesias", "10 iglesias"], correcta: 0 },
            { pregunta: "¿Cuáles son algunas de las 7 iglesias de Apocalipsis?", opciones: ["Éfeso, Esmirna, Pérgamo, Tiatira, Sardis, Filadelfia, Laodicea", "Roma, Corinto, Galacia", "Jerusalén, Antioquía, Nazaret", "Atenas, Esparta, Macedonia"], correcta: 0 },
            { pregunta: "¿Qué significa la palabra 'Apocalipsis'?", opciones: ["Revelación o desvelamiento", "Destrucción final", "Fin del mundo", "Juicio de fuego"], correcta: 0 },
            { pregunta: "¿Qué flor o árbol de la vida se menciona a orillas del río en la Nueva Jerusalén en Apocalipsis 22?", opciones: ["El Árbol de la Vida que da 12 frutos", "El Olivo milenario", "El Cedro del cielo", "La Higuera dorada"], correcta: 0 },
            { pregunta: "¿Qué prometa Dios secar en la Nueva Jerusalén según Apocalipsis 21?", opciones: ["Toda lágrima de los ojos de ellos; y ya no habrá muerte ni llanto", "Los ríos de la tierra", "El mar terrenal únicamente", "El sol"], correcta: 0 },
            { pregunta: "¿A quién le escribió Pablo la epístola pidiéndole que recibiera al esclavo fugitivo Onésimo como a un hermano?", opciones: ["Filemón", "Tito", "Timoteo", "Gayo"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba el esclavo que se convirtió bajo el ministerio de Pablo en la cárcel?", opciones: ["Onésimo", "Tíquico", "Epafrodito", "Arquipo"], correcta: 0 },
            { pregunta: "¿Qué carta del Nuevo Testamento destaca a Jesús como el Gran Sumo Sacerdote según el orden de Melquisedec?", opciones: ["Hebreos", "Romanos", "Gálatas", "Colosenses"], correcta: 0 },
            { pregunta: "¿Cómo define Hebreos 11:1 la fe?", opciones: ["Es la certeza de lo que se espera, la convicción de lo que no se ve", "Es creer sin pensar", "Es tener suerte", "Es la fuerza del pensamiento"], correcta: 0 },
            { pregunta: "¿Qué gran lista de personajes bíblicos se halla en Hebreos 11?", opciones: ["Los héroes de la fe", "Los reyes de Judá", "Los jueces de Israel", "Los apóstoles"], correcta: 0 },
            { pregunta: "¿Qué personaje por la fe ofreció a Dios más excelente sacrificio que Caín?", opciones: ["Abel", "Enoc", "Noé", "Abraham"], correcta: 0 },
            { pregunta: "¿Qué personaje por la fe fue traspuesto para no ver muerte?", opciones: ["Enoc", "Elías", "Moisés", "Samuel"], correcta: 0 },
            { pregunta: "¿Qué pasaje del Nuevo Testamento dice: 'Toda la Escritura es inspirada por Dios y útil para enseñar'?", opciones: ["2 Timoteo 3:16", "Juan 3:16", "Romanos 8:28", "Filipenses 4:13"], correcta: 0 },
            { pregunta: "¿Cuál es el versículo más conocido que resume el amor de Dios enviando a su Hijo?", opciones: ["Juan 3:16", "Gálatas 2:20", "Romanos 3:23", "1 Juan 4:8"], correcta: 0 },
            { pregunta: "¿Qué dice Juan 3:16?", opciones: ["Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito...", "En el principio era el Verbo...", "El Señor es mi pastor...", "Yo soy el camino..."], correcta: 0 },
            { pregunta: "¿Qué capítulo de Romanos habla de que 'ninguna condenación hay para los que están en Cristo Jesús'?", opciones: ["Romanos 8", "Romanos 3", "Romanos 12", "Romanos 5"], correcta: 0 },
            { pregunta: "¿Qué dice Romanos 8:28 sobre las cosas que les suceden a los que aman a Dios?", opciones: ["Todas las cosas les ayudan a bien", "No tendrán ningún problema", "Serán ricos siempre", "No sufrirán jamás"], correcta: 0 },
            { pregunta: "¿Qué carta de Pablo habla de no amoldarse a este mundo sino transformarse mediante el renuevo de la mente?", opciones: ["Romanos (Capítulo 12)", "Gálatas", "1 Tesalonicenses", "2 Corintios"], correcta: 0 },
            { pregunta: "¿Qué frutos del Espíritu se mencionan en Gálatas 5:22-23?", opciones: ["Amor, gozo, paz, paciencia, benignidad, bondad, fe, mansedumbre, templanza", "Sabiduría, riqueza, poder", "Fe, esperanza y caridad únicamente", "Fuerza, salud y longevidad"], correcta: 0 },
            { pregunta: "¿Qué apóstol escribió: 'Dios es amor' en su primera epístola?", opciones: ["Juan", "Pablo", "Pedro", "Santiago"], correcta: 0 },
            { pregunta: "¿Qué apóstol era apodado 'Hijo de Consolación' por su generosidad?", opciones: ["Bernabé", "Marcos", "Silas", "Lucas"], correcta: 0 },
            { pregunta: "¿Quién acompañó a Pablo en su segundo viaje misionero tras separarse de Bernabé?", opciones: ["Silas", "Marcos", "Barnabás", "Demas"], correcta: 0 },
            { pregunta: "¿Qué joven de Listra se unió a Pablo y Silas en su viaje y tenía madre judía y padre griego?", opciones: ["Timoteo", "Tito", "Lucas", "Apolo"], correcta: 0 },
            { pregunta: "¿Qué abuela y madre instruyeron a Timoteo en las Sagradas Escrituras desde niño?", opciones: ["Su abuela Loida y su madre Eunice", "Su madre Marta y abuela María", "Sara y Rebeca", "Ester y Rut"], correcta: 0 },
            { pregunta: "¿A qué isla envió Pablo a Tito para ordenar ancianos en cada ciudad?", opciones: ["Creta", "Chipre", "Malta", "Sicilia"], correcta: 0 },
            { pregunta: "¿En qué isla naufragó la nave en la que Pablo viajaba prisionero a Roma?", opciones: ["Malta", "Patmos", "Creta", "Rodas"], correcta: 0 },
            { pregunta: "¿Qué animal mordió la mano de Pablo en la isla de Malta sin hacerle daño?", opciones: ["Una víbora / serpiente", "Un escorpión", "Un perro", "Un ciempiés"], correcta: 0 },
            { pregunta: "¿Cómo reaccionaron los habitantes de Malta al ver que Pablo no sufrió daño por la víbora?", opciones: ["Dijeron que era un dios", "Tuvieron miedo y huyeron", "Lo metieron preso", "No le hicieron caso"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba el hombre principal de la isla de Malta cuyo padre fue sanado por Pablo?", opciones: ["Publio", "Julio", "Gayo", "Teófilo"], correcta: 0 },
            { pregunta: "¿A quién va dirigido tanto el Evangelio de Lucas como el libro de Hechos?", opciones: ["A Excelentísimo Teófilo", "A la iglesia de Roma", "A los doce apóstoles", "Al emperador César"], correcta: 0 },
            { pregunta: "¿Qué profetisa de avanzada edad alabó a Dios al ver al niño Jesús en el Templo?", opciones: ["Ana", "Isabel", "María", "Marta"], correcta: 0 },
            { pregunta: "¿Qué anciano piadoso sostuvo al niño Jesús en el Templo diciendo que sus ojos habían visto la salvación?", opciones: ["Simeón", "Zacarías", "Nicodemo", "Gamaliel"], correcta: 0 },
            { pregunta: "¿Quién era el esposo de Elizabeth y padre de Juan el Bautista?", opciones: ["Zacarías", "José", "Simeón", "Sacerdote Anás"], correcta: 0 },
            { pregunta: "¿Por qué quedó mudo Zacarías hasta el nacimiento de Juan el Bautista?", opciones: ["Por dudar del anuncio del ángel Gabriel", "Por una enfermedad", "Por mandato del Rey", "Por decisión propia"], correcta: 0 },
            { pregunta: "¿Qué relación familiar tenían María la madre de Jesús y Elizabeth la madre de Juan?", opciones: ["Parientas / Primas", "Hermanas", "Madre e hija", "No tenían relación"], correcta: 0 },
            { pregunta: "¿Qué canto de alabanza proclamó María al visitar a su parienta Elizabeth?", opciones: ["El Magníficat", "El Nunc Dimittis", "El Cántico de Moisés", "El Salmo 23"], correcta: 0 },
            { pregunta: "¿En qué libro del Nuevo Testamento se habla de la armadura completa del cristiano?", opciones: ["Efesios", "Filipenses", "Colosenses", "Hebreos"], correcta: 0 },
            { pregunta: "¿Qué carta enfatiza que la fe debe demostrarse con buenas obras hacia los demás?", opciones: ["Santiago", "Gálatas", "1 Juan", "2 Corintios"], correcta: 0 },
            { pregunta: "¿Qué libro del Nuevo Testamento describe las 7 copas, las 7 trompetas y los 7 sellos?", opciones: ["Apocalipsis", "Hechos", "Daniel", "Ezequiel"], correcta: 0 },
            { pregunta: "¿Qué apóstol resucitó a la piadosa mujer Dorcas (Tabita) en Jope?", opciones: ["Pedro", "Pablo", "Juan", "Felipe"], correcta: 0 },
            { pregunta: "¿A qué se dedicaba Dorcas en Jope antes de morir y ser resucitada por Pedro?", opciones: ["Hacer túnicas y vestidos para las viudas y necesitados", "Vender pan", "Escribir cartas", "Cuidar el templo"], correcta: 0 },
            { pregunta: "¿Qué hombre cayó de una ventana en Troas mientras Pablo predicaba un discurso largo?", opciones: ["Eutico", "Tíquico", "Trófimo", "Erasto"], correcta: 0 },
            { pregunta: "¿Qué le ocurrió a Eutico tras caer desde el tercer piso?", opciones: ["Murió por la caída, pero Pablo se abrazó a él y resucitó", "Solo se fracturó un brazo", "Huyó asustado", "No le pasó nada"], correcta: 0 },
            { pregunta: "¿Qué carta de Pablo dice: 'Todo lo puedo en Cristo que me fortalece'?", opciones: ["Filipenses (4:13)", "Gálatas", "Efesios", "Colosenses"], correcta: 0 },
            { pregunta: "¿Qué apóstol escribió el libro de Apocalipsis mientras estaba prisionero?", opciones: ["Juan", "Pablo", "Pedro", "Mateo"], correcta: 0 },
            { pregunta: "¿En qué evangelio se relata la parábola de las 10 vírgenes (5 prudentes y 5 insensatas)?", opciones: ["Mateo (Capítulo 25)", "Marcos", "Lucas", "Juan"], correcta: 0 },
            { pregunta: "¿Qué les faltó a las 5 vírgenes insensatas en sus lámparas?", opciones: ["Aceite", "Mecha", "Fuego", "Cera"], correcta: 0 },
            { pregunta: "¿Qué representa el aceite en la parábola de las 10 vírgenes?", opciones: ["La preparación espiritual y presencia del Espíritu Santo", "El dinero", "El conocimiento humano", "Las obras externas"], correcta: 0 },
            { pregunta: "¿Qué apóstol dijo: 'He peleado la buena batalla, he acabado la carrera, he guardado la fe'?", opciones: ["Pablo (2 Timoteo 4:7)", "Pedro", "Juan", "Santiago"], correcta: 0 },
            { pregunta: "¿A quién llama la Biblia el 'Padre de la Fe' citado en el Nuevo Testamento?", opciones: ["Abraham", "Moisés", "David", "Adán"], correcta: 0 },
            { pregunta: "¿Qué apóstol usó la frase: 'Sed imitadores de mí, así como yo de Cristo'?", opciones: ["Pablo", "Pedro", "Juan", "Santiago"], correcta: 0 },
            { pregunta: "¿En qué libro se describe la venida de la Nueva Jerusalén descendiendo del cielo?", opciones: ["Apocalipsis (Capítulo 21)", "Hechos", "Hebreos", "1 Tesalonicenses"], correcta: 0 },
            { pregunta: "¿Qué carta breve del Nuevo Testamento tiene solo 1 capítulo y advierte contra los falsos maestros?", opciones: ["Judas", "2 Juan", "3 Juan", "Filemón"], correcta: 0 },
            { pregunta: "¿Qué acontecimiento esperamos los creyentes según 1 Tesalonicenses 4?", opciones: ["La segunda venida de Cristo y la transformación de la iglesia", "La reconstrucción de Babilonia", "El reinado de Salomón", "Un nuevo diluvio"], correcta: 0 },
            { pregunta: "¿Quién es la cabeza de la Iglesia según el Nuevo Testamento?", opciones: ["Jesucristo", "El apóstol Pedro", "El rey de Roma", "El consejo de ancianos"], correcta: 0 },
            { pregunta: "¿Qué regalo inmerecido de Dios se enfatiza en Efesios 2:8 ('Porque por gracia sois salvos...')?", opciones: ["La Gracia divina", "La ley de Moisés", "La sabiduría terrenal", "La riqueza"], correcta: 0 },
            { pregunta: "¿Cuál es el mensaje central de todo el Nuevo Testamento?", opciones: ["La salvación y vida eterna mediante Jesucristo", "Las guerras del antiguo Israel", "Las leyes del templo", "Las historias del desierto"], correcta: 0 }
        ]
    },
    "antiguo_testamento": {
        titulo: "🏛️ Antiguo Testamento",
        preguntas: [
            { pregunta: "¿Cuántos libros componen el Antiguo Testamento?", opciones: ["39 libros", "27 libros", "66 libros", "40 libros"], correcta: 0 },
            { pregunta: "¿Cuál es el primer libro del Antiguo Testamento?", opciones: ["Génesis", "Éxodo", "Levítico", "Salmos"], correcta: 0 },
            { pregunta: "¿Cómo se conocen los primeros 5 libros del Antiguo Testamento escritos por Moisés?", opciones: ["El Pentateuco / La Ley (Torá)", "Los Libros Poéticos", "Los Profetas Mayores", "Las Epístolas"], correcta: 0 },
            { pregunta: "¿Cuáles son los 5 libros del Pentateuco?", opciones: ["Génesis, Éxodo, Levítico, Números, Deuteronomio", "Josué, Jueces, Rut, 1 Samuel, 2 Samuel", "Salmos, Proverbios, Eclesiastés, Cantares, Job", "Isaías, Jeremías, Lamentaciones, Ezequiel, Daniel"], correcta: 0 },
            { pregunta: "¿Quién fue el primer hombre creado por Dios?", opciones: ["Adán", "Noé", "Abraham", "Seth"], correcta: 0 },
            { pregunta: "¿Quién fue la primera mujer creada por Dios?", opciones: ["Eva", "Sara", "Agar", "Rebeca"], correcta: 0 },
            { pregunta: "¿Quién mató a su hermano Abel por envidia?", opciones: ["Caín", "Seth", "Lamec", "Jubal"], correcta: 0 },
            { pregunta: "¿A qué patriarca le ordenó Dios construir un arca para salvar a su familia del diluvio?", opciones: ["Noé", "Abraham", "Matusalén", "Enoc"], correcta: 0 },
            { pregunta: "¿Cuántas personas se salvaron dentro del arca de Noé?", opciones: ["8 personas", "4 personas", "12 personas", "70 personas"], correcta: 0 },
            { pregunta: "¿Cómo se llamaban los tres hijos de Noé?", opciones: ["Sem, Cam y Japaf", "Abraham, Isaac y Jacob", "Moisés, Aarón y Hur", "Caín, Abel y Seth"], correcta: 0 },
            { pregunta: "¿Qué gran torre intentaron construir los hombres para llegar al cielo antes de que Dios confundiera sus lenguas?", opciones: ["La Torre de Babel", "La Torre de David", "El Templo de Babilonia", "La Pirámide de Giza"], correcta: 0 },
            { pregunta: "¿A qué hombre llamó Dios fuera de Ur de los Caldeos prometiéndole hacer de él una gran nación?", opciones: ["Abraham", "Lot", "Terah", "Nahor"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba la esposa de Abraham?", opciones: ["Sara", "Rebeca", "Raquel", "Lea"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba el hijo de la promesa nacido de Abraham y Sara en su vejez?", opciones: ["Isaac", "Ismael", "Jacob", "Esaú"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba el hijo que Abraham tuvo con la sierva Agar?", opciones: ["Ismael", "Isaac", "Moab", "Amón"], correcta: 0 },
            { pregunta: "¿En qué monte le pidió Dios a Abraham que probara su fe ofreciendo a Isaac?", opciones: ["Monte Moriah", "Monte Sinaí", "Monte Ararat", "Monte Carmelo"], correcta: 0 },
            { pregunta: "¿Qué animal proveyó Dios para el sacrificio en sustitución de Isaac?", opciones: ["Un carnero trabado en un zarzal", "Un cordero sin mancha", "Un buey", "Una paloma"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba la esposa de Isaac?", opciones: ["Rebeca", "Sara", "Raquel", "Lea"], correcta: 0 },
            { pregunta: "¿Cómo se llamaban los dos hijos gemelos de Isaac y Rebeca?", opciones: ["Esaú y Jacob", "Perez y Zera", "Efraín y Manasés", "Moisés y Aarón"], correcta: 0 },
            { pregunta: "¿Por qué vendió Esaú su primogenitura a su hermano Jacob?", opciones: ["Por un plato de guisado de lentejas rojo", "Por monedas de plata", "Por un rebaño", "Por una túnica"], correcta: 0 },
            { pregunta: "¿Cómo se llamaban las dos hermanas esposas de Jacob?", opciones: ["Lea y Raquel", "Marta y María", "Sara y Agar", "Orfa y Rut"], correcta: 0 },
            { pregunta: "¿Cuántos hijos varones tuvo Jacob, que dieron origen a las tribus de Israel?", opciones: ["12 hijos", "10 hijos", "7 hijos", "14 hijos"], correcta: 0 },
            { pregunta: "¿Cuál era el hijo favorito de Jacob a quien le regaló una túnica de colores?", opciones: ["José", "Benjamín", "Judá", "Rubén"], correcta: 0 },
            { pregunta: "¿A qué país fue llevado José como esclavo tras ser vendido por sus hermanos?", opciones: ["Egipto", "Babilonia", "Asiria", "Canaán"], correcta: 0 },
            { pregunta: "¿A qué cargo llegó José en Egipto tras interpretar los sueños del Faraón?", opciones: ["Gobernador / Segundo al mando de Egipto", "Capitán del ejército", "Sacerdote principal", "Jefe de los sirvientes"], correcta: 0 },
            { pregunta: "¿Qué significaban las 7 vacas gordas y 7 vacas flacas en el sueño del Faraón?", opciones: ["7 años de abundancia seguidos de 7 años de gran hambre", "7 reyes prósperos", "7 batallas ganadas", "7 cosechas de trigo"], correcta: 0 },
            { pregunta: "¿Qué profeta nació en Egipto, fue salvado de las aguas del Nilo en una cesta y libertó a Israel?", opciones: ["Moisés", "Aarón", "Josué", "Samuel"], correcta: 0 },
            { pregunta: "¿Quién rescató a Moisés del río Nilo cuando era un bebé?", opciones: ["La hija del Faraón", "La esposa de Potifar", "Su madre Jocabed", "Miriam"], correcta: 0 },
            { pregunta: "¿En qué forma se le apareció Dios a Moisés en el monte Horeb?", opciones: ["En una zarza que ardía y no se consumía", "En una gran nube negra", "En un río de fuego", "En un sueño"], correcta: 0 },
            { pregunta: "¿Cuántas plagas envió Dios sobre Egipto para que el Faraón dejara ir a su pueblo?", opciones: ["10 plagas", "7 plagas", "12 plagas", "5 plagas"], correcta: 0 },
            { pregunta: "¿Cuál fue la décima y última plaga sobre Egipto?", opciones: ["La muerte de los primogénitos", "Las langostas", "La conversión del agua en sangre", "Las tinieblas"], correcta: 0 },
            { pregunta: "¿Con qué fiesta recordaba el pueblo de Israel su salida de Egipto y la protección del ángel?", opciones: ["La Pascua", "Pentecostés", "Los Tabernáculos", "El Purim"], correcta: 0 },
            { pregunta: "¿Qué mar abrió Dios milagrosamente a través de la vara de Moisés?", opciones: ["El Mar Rojo", "El Mar Muerto", "El Mar de Galilea", "El Mar Mediterráneo"], correcta: 0 },
            { pregunta: "¿En qué monte entregó Dios los Diez Mandamientos grabados en tablas de piedra?", opciones: ["Monte Sinaí", "Monte Ararat", "Monte Nebo", "Monte Carmelo"], correcta: 0 },
            { pregunta: "¿Qué construyeron los israelitas para adorar mientras Moisés estaba en el monte Sinaí?", opciones: ["Un becerro de oro", "Una estatua de baal", "Un altar de madera", "Una pirámide"], correcta: 0 },
            { pregunta: "¿Cómo se llamaba el santuario móvil que construyó Israel en el desierto según el diseño de Dios?", opciones: ["El Tabernáculo", "El Templo de Salomón", "La Sinagoga", "El Palacio"], correcta: 0 },
            { pregunta: "¿Qué objeto sagrado se guardaba en el Lugar Santísimo del Tabernáculo?", opciones: ["El Arca del Pacto", "El Altar del Incienso", "El Candelabro de Oro", "La Mesa del Pan"], correcta: 0 },
            { pregunta: "¿Qué tres cosas contenía el Arca del Pacto en su interior?", opciones: ["Las tablas de la Ley, una vasija con maná y la vara de Aarón que floreció", "La corona de David y oro", "Las vestiduras de Moisés", "El libro de Josué"], correcta: 0 },
            { pregunta: "¿De qué dos espías fieles dependió el informe positivo sobre la tierra prometida?", opciones: ["Josué y Caleb", "Moisés y Aarón", "Gedeón y Sansón", "Hur y Nadab"], correcta: 0 },
            { pregunta: "¿Desde qué monte vio Moisés la tierra prometida antes de morir?", opciones: ["Monte Nebo", "Monte Sinaí", "Monte Olivos", "Monte Hermón"], correcta: 0 },
            { pregunta: "¿Quién sucedió a Moisés como líder militar y espiritual para conquistar Canaán?", opciones: ["Josué", "Caleb", "Gedeón", "Eleazar"], correcta: 0 },
            { pregunta: "¿Qué río se dividió milagrosamente cuando los sacerdotes con el Arca pusieron sus pies en el agua?", opciones: ["El río Jordán", "El río Nilo", "El río Éufrates", "El río Tigris"], correcta: 0 },
            { pregunta: "¿Qué mujer de Jericó escondió a los espías israelitas en su casa y fue salvada?", opciones: ["Rahab", "Rut", "Débora", "Jael"], correcta: 0 },
            { pregunta: "¿Cómo cayeron los murallones de la ciudad de Jericó?", opciones: ["Tras dar vueltas 7 días y tocar las trompetas con un gran grito", "Con un terremoto de noche", "Con catapultas de fuego", "Mediante un sitio de tres años"], correcta: 0 },
            { pregunta: "¿Cómo se llamaban los líderes gobernantes que Dios levantó en Israel antes de tener reyes?", opciones: ["Los Jueces", "Los Faraones", "Los Emperadores", "Los Patriarcas"], correcta: 0 },
            { pregunta: "¿Qué profetisa y jueza gobernó a Israel debajo de una palmera y fue a la batalla con Barac?", opciones: ["Débora", "Jael", "Miriam", "Noemí"], correcta: 0 },
            { pregunta: "¿Quién eliminó al general ejército enemigo Sísara clavándole una estaca de tienda?", opciones: ["Jael", "Débora", "Rut", "Ana"], correcta: 0 },
            { pregunta: "¿Qué juez redujo su ejército de 32,000 a solo 300 hombres usando cantaros y antorchas?", opciones: ["Gedeón", "Sansón", "Jefté", "Otoniel"], correcta: 0 },
            { pregunta: "¿Qué juez tenía una fuerza sobrenatural en su cabello dado por el Espíritu de Dios?", opciones: ["Sansón", "Gedeón", "Samuel", "Abimelec"], correcta: 0 },
            { pregunta: "¿Qué mujer filistea traicionó a Sansón descubriendo el secreto de su fuerza?", opciones: ["Dalila", "Jezabel", "Atalía", "Vasti"], correcta: 0 },
            { pregunta: "¿Qué moabita piadosa dijo a su suegra Noemí: 'Tu pueblo será mi pueblo, y tu Dios mi Dios'?", opciones: ["Rut", "Orfa", "Agar", "Sefora"], correcta: 0 },
            { pregunta: "¿Quién fue el pariente redentor que se casó con Rut en Belén?", opciones: ["Booz", "Obed", "Isaí", "Elimelec"], correcta: 0 },
            { pregunta: "¿Quién fue el bisnieto de Rut y Booz que llegó a ser el gran rey de Israel?", opciones: ["El rey David", "El rey Saúl", "El rey Salomón", "El rey Ezequías"], correcta: 0 },
            { pregunta: "¿Qué mujer piadosa oró fervientemente en el Tabernáculo pidiendo un hijo y Dios le dio a Samuel?", opciones: ["Ana", "Penina", "Noemí", "Isabel"], correcta: 0 },
            { pregunta: "¿Quién era el anciano Sumo Sacerdote que crió al niño Samuel en el Tabernáculo de Silo?", opciones: ["Elí", "Aarón", "Abiatar", "Sadooc"], correcta: 0 },
            { pregunta: "¿Quién fue el último juez de Israel y el profeta que ungió a los primeros dos reyes?", opciones: ["Samuel", "Nathan", "Gad", "Elías"], correcta: 0 },
            { pregunta: "¿Quién fue el primer rey ungido de Israel?", opciones: ["Saúl", "David", "Salomón", "Jeroboam"], correcta: 0 },
            { pregunta: "¿De qué tribu de Israel procedía el rey Saúl?", opciones: ["Tribu de Benjamín", "Tribu de Judá", "Tribu de Leví", "Tribu de Efraín"], correcta: 0 },
            { pregunta: "¿En qué ciudad nació David y fue ungido rey por el profeta Samuel siendo un joven pastor?", opciones: ["Belén", "Jerusalén", "Hebrón", "Silo"], correcta: 0 },
            { pregunta: "¿A qué gigante filisteo de Gat desafió y venció el joven David en el valle de Elah?", opciones: ["Goliat", "Isbi-benob", "Saph", "Lahmi"], correcta: 0 },
            { pregunta: "¿Quién era el mejor amigo de David, hijo del rey Saúl?", opciones: ["Jonatán", "Abner", "Joab", "Is-boset"], correcta: 0 },
            { pregunta: "¿Qué ciudad conquistó David a los jebuseos y la nombró la capital de su reino?", opciones: ["Jerusalén (Ciudad de David / Sión)", "Hebrón", "Samaria", "Jericó"], correcta: 0 },
            { pregunta: "¿Qué rey deseaba construir un Templo para Dios pero Dios le dijo que lo haría su hijo?", opciones: ["David", "Saúl", "Salomón", "Ezequías"], correcta: 0 },
            { pregunta: "¿Qué rey famoso por su sabiduría edificó el primer Templo de Jerusalén?", opciones: ["Salomón", "David", "Roboam", "Josías"], correcta: 0 },
            { pregunta: "¿Qué libro poético contiene 150 cánticos y oraciones compuestas en gran parte por David?", opciones: ["El libro de los Salmos", "Proverbios", "Eclesiastés", "Cantares"], correcta: 0 },
            { pregunta: "¿Cómo empieza el conocido Salmo 23 escrito por David?", opciones: ["Jehová es mi pastor; nada me faltará", "Dios es nuestro amparo y fortaleza", "Alabaré a Jehová con todo mi corazón", "El cielo declara la gloria de Dios"], correcta: 0 },
            { pregunta: "¿Qué libro del Antiguo Testamento recopila miles de consejos sabios para la vida cotidiana?", opciones: ["Proverbios", "Eclesiastés", "Job", "Lamentaciones"], correcta: 0 },
            { pregunta: "¿Qué rey escribió los libros de Proverbios, Eclesiastés y Cantares?", opciones: ["Salomón", "David", "Ezequías", "Manoa"], correcta: 0 },
            { pregunta: "¿En qué dos reinos se dividió la nación de Israel tras la muerte de Salomón?", opciones: ["Reino de Israel (Norte) y Reino de Judá (Sur)", "Galilea y Judea", "Egipto y Siria", "Samaria y Babilonia"], correcta: 0 },
            { pregunta: "¿Cuál fue la capital del Reino del Norte (Israel)?", opciones: ["Samaria", "Jerusalén", "Jericó", "Tirsa"], correcta: 0 },
            { pregunta: "¿Cuál fue la capital del Reino del Sur (Judá)?", opciones: ["Jerusalén", "Samaria", "Hebrón", "Siquem"], correcta: 0 },
            { pregunta: "¿Qué profeta del Reino del Norte enfrentó a los 450 profetas de Baal en el Monte Carmelo?", opciones: ["Elías", "Eliseo", "Isaías", "Jeremías"], correcta: 0 },
            { pregunta: "¿Cómo respondió Dios a la oración de Elías en el Monte Carmelo?", opciones: ["Hizo descender fuego del cielo que consumió el holocausto y el agua", "Envió un terremoto", "Hizo llover de inmediato", "Apareció un ángel visible"], correcta: 0 },
            { pregunta: "¿Quién fue el profeta y sucesor de Elías que recibió una doble porción de su espíritu?", opciones: ["Eliseo", "Isaías", "Oseas", "Amós"], correcta: 0 },
            { pregunta: "¿Qué milagro hizo Eliseo con el hacha que se le cayó a un joven al agua?", opciones: ["Hizo flotar el hierro del hacha sobre el agua", "Convirtió el agua en hielo", "Secó el río", "Sacó el hacha con la mano"], correcta: 0 },
            { pregunta: "¿Qué rey malvado de Israel y qué reina fenicia promovieron el culto a Baal?", opciones: ["El rey Acab y la reina Jezabel", "Jeroboam y Vasti", "Manasés y Atalía", "Omri y Herodías"], correcta: 0 },
            { pregunta: "¿Qué profeta es conocido como el 'Profeta Mesiánico' por sus profecías sobre el nacimiento y sufrimiento de Cristo?", opciones: ["Isaías", "Jeremías", "Ezequiel", "Daniel"], correcta: 0 },
            { pregunta: "¿Qué profeta es conocido como el 'Profeta Llorón' por sus sufrimientos al advertir a Jerusalén?", opciones: ["Jeremías", "Isaías", "Joel", "Amós"], correcta: 0 },
            { pregunta: "¿Qué imperio destruyó el Reino del Norte (Israel) en el año 722 a.C.?", opciones: ["El Imperio Asirio", "El Imperio Babilónico", "El Imperio Persa", "El Imperio Romano"], correcta: 0 },
            { pregunta: "¿Qué rey de Babilonia destruyó el Templo de Jerusalén y llevó cautivo a Judá?", opciones: ["Nabucodonosor II", "Ciro el Grande", "Dario el Medo", "Baltasar"], correcta: 0 },
            { pregunta: "¿Qué cuatro jóvenes hebreos mantuvieron su fe y pureza en la corte de Babilonia?", opciones: ["Daniel, Ananías, Misael y Azarías (Beltsasar, Sadrac, Mesac y Abed-nego)", "Moisés, Aarón, Josué y Caleb", "Esdras, Nehemías, Mardoqueo y Zorobabel", "Isaías, Jeremías, Ezequiel y Daniel"], correcta: 0 },
            { pregunta: "¿Qué les ocurrió a Sadrac, Mesac y Abed-nego cuando fueron arrojados al horno de fuego ardiente?", opciones: ["No sufrieron daño alguno y caminaban junto a una cuarta persona semejante a un hijo de los dioses", "Se quemaron la ropa", "Escape por una puerta trasera", "El horno se apago con agua"], correcta: 0 },
            { pregunta: "¿Qué profeta interpretó la escritura en la pared ('MENE, MENE, TEKEL, PARSIN') durante el banquete del rey Baltasar?", opciones: ["Daniel", "Ezequiel", "Jeremías", "Hageo"], correcta: 0 },
            { pregunta: "¿Por qué fue arrojado Daniel al foso de los leones?", opciones: ["Por orar a Dios tres veces al día desafiando el decreto del rey Darío", "Por robar el tesoro real", "Por negarse a luchar", "Por destruir estatuas"], correcta: 0 },
            { pregunta: "¿Cómo sobrevivió Daniel la noche en el foso de los leones?", opciones: ["Dios envió su ángel y cerró la boca de los leones", "Los leones estaban dormidos por drogas", "Daniel mató a los leones", "Escapó por una grieta"], correcta: 0 },
            { pregunta: "¿Qué profeta fue enviado a predicar arrepentimiento a la gran ciudad enemiga de Nínive?", opciones: ["Jonás", "Naúm", "Sofonías", "Abdías"], correcta: 0 },
            { pregunta: "¿Qué hizo la gente de Nínive al escuchar la predicación de Jonás?", opciones: ["Se arrepintieron, hicieron ayuno y se vistieron de cilicio", "Mataron a Jonás", "Se burlaron del profeta", "Huyeron de la ciudad"], correcta: 0 },
            { pregunta: "¿Qué copa de reconstrucción dirigió Nehemías en Jerusalén?", opciones: ["Los muros y murallas de Jerusalén", "El Palacio Real", "La Torre de Babel", "El estanque de Siloé"], correcta: 0 },
            { pregunta: "¿Qué sacerdote y escriba guio al pueblo a leer y entender la Ley de Dios tras volver del exilio?", opciones: ["Esdras", "Nehemías", "Zorobabel", "Malaquías"], correcta: 0 },
            { pregunta: "¿Quién fue el último profeta del Antiguo Testamento antes del periodo de 400 años de silencio?", opciones: ["Malaquías", "Zacarías", "Hageo", "Sofonías"], correcta: 0 },
            { pregunta: "¿Qué hombre justo de la tierra de Uz sufrió grandes pruebas de salud y pérdida pero no maldijo a Dios?", opciones: ["Job", "Abraham", "Lot", "Noé"], correcta: 0 },
            { pregunta: "¿Qué le respondió Dios a Job cuando este pedía explicaciones sobre su sufrimiento?", opciones: ["Le habló desde un torbellino mostrando la grandeza de la Creación", "Le mandó un ángel con una carta", "Le devolvió todo sin hablar", "No le respondió nada"], correcta: 0 },
            { pregunta: "¿Qué prometió Dios al final de la historia de Job?", opciones: ["Bendijo su postrer estado el doble de lo que tenía antes", "Lo nombró rey de Uz", "Le dio un palacio de oro", "Lo llevó al cielo en vida"], correcta: 0 },
            { pregunta: "¿Qué reina pagana fue esposa del rey Acab e intentó matar a los profetas de Dios?", opciones: ["Jezabel", "Vasti", "Atalía", "Herodías"], correcta: 0 },
            { pregunta: "¿Qué reina persa de origen judío arriesgó su vida presentándose ante el rey Asuero para salvar a su pueblo?", opciones: ["Ester", "Rut", "Vasti", "Ana"], correcta: 0 },
            { pregunta: "¿Quién era el malvado primer ministro persa que planeaba exterminar a todos los judíos en tiempos de Ester?", opciones: ["Amán", "Mardoqueo", "Bigtán", "Teres"], correcta: 0 },
            { pregunta: "¿Quién era el tío/primo de Ester que la crió y la animó diciendo: '¿Y quién sabe si para esta hora has llegado al reino'?", opciones: ["Mardoqueo", "Nehemías", "Esdras", "Zorobabel"], correcta: 0 },
            { pregunta: "¿Qué fiesta judía se celebra en memoria de la victoria y liberación en tiempos de la reina Ester?", opciones: ["La fiesta de Purim", "La fiesta de Hanukkah", "La fiesta de Pentecostés", "La fiesta de los Panes sin Levadura"], correcta: 0 },
            { pregunta: "¿Qué profeta vio una visión del carro de Dios con seres vivientes y ruedas llenas de ojos?", opciones: ["Ezequiel", "Isaías", "Daniel", "Zacarías"], correcta: 0 },
            { pregunta: "¿A qué se refiere el Antiguo Testamento cuando habla de la promesa del 'Nuevo Pacto' en Jeremías 31?", opciones: ["Escribir la ley de Dios en el corazón de las personas", "Una nueva tierra en Egipto", "Un nuevo templo de oro", "Una nueva ley militar"], correcta: 0 }
        ]
    }
};

// --- ALGORITMO FISHER-YATES: Extrae N preguntas aleatorias de cualquier temática ---
function obtenerPreguntasAleatorias(keyTematica, cantidad = 20) {
    if (!tematicasData[keyTematica]) return [];
    
    const bancoOriginal = tematicasData[keyTematica].preguntas;
    const copiaBanco = [...bancoOriginal];

    for (let i = copiaBanco.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [copiaBanco[i], copiaBanco[j]] = [copiaBanco[j], copiaBanco[i]];
    }

    return copiaBanco.slice(0, cantidad);
}
