// preguntas.js
const baseDeDatos = {
    "Jesús": [
        { p: "¿En qué ciudad nació Jesús?", o: ["Nazaret", "Belén", "Jerusalén", "Jericó"], c: 1 },
        { p: "¿Cuál fue el primer milagro de Jesús?", o: ["Caminar sobre el agua", "Sanar a un ciego", "Agua en vino", "Multiplicar panes"], c: 2 },
        { p: "¿En qué río fue bautizado Jesús?", o: ["Nilo", "Éufrates", "Jordán", "Tigris"], c: 2 },
        { p: "¿Quién bautizó a Jesús?", o: ["Pedro", "Juan el Bautista", "Mateo", "Pablo"], c: 1 },
        { p: "¿Cuántos apóstoles principales eligió Jesús?", o: ["10", "12", "7", "40"], c: 1 },
        { p: "¿Quién traicionó a Jesús?", o: ["Pedro", "Judas Iscariote", "Tomás", "Juan"], c: 1 },
        { p: "¿Por cuántas monedas fue traicionado Jesús?", o: ["10", "20", "30", "40"], c: 2 },
        { p: "¿A quién resucitó Jesús después de cuatro días en el sepulcro?", o: ["Lázaro", "Jairo", "Zaqueo", "Nicodemo"], c: 0 },
        { p: "¿Qué usó Jesús para alimentar a cinco mil personas?", o: ["7 panes y 2 peces", "5 panes y 2 peces", "Maná del cielo", "Uvas y vino"], c: 1 },
        { p: "¿Qué discípulo negó a Jesús tres veces?", o: ["Juan", "Judas", "Pedro", "Andrés"], c: 2 },
        { p: "¿Cómo se llama el monte donde crucificaron a Jesús?", o: ["Sinaí", "Carmelo", "Gólgota", "Tabor"], c: 2 },
        { p: "¿Qué le pusieron a Jesús en la cabeza antes de crucificarlo?", o: ["Corona de oro", "Corona de espinas", "Un manto real", "Aceite"], c: 1 },
        { p: "¿A qué edad se quedó Jesús en el templo hablando con los doctores?", o: ["10 años", "12 años", "15 años", "7 años"], c: 1 },
        { p: "¿Qué oficio tenía Jesús antes de iniciar su ministerio?", o: ["Pescador", "Pastor de ovejas", "Carpintero", "Cobrador de impuestos"], c: 2 },
        { p: "¿Cómo se llamaba el hombre bajito que subió a un árbol para ver a Jesús?", o: ["Bartimeo", "Zaqueo", "Nicodemo", "Cornelio"], c: 1 },
        { p: "¿Qué discípulo caminó sobre el agua hacia Jesús?", o: ["Pedro", "Juan", "Santiago", "Tomás"], c: 0 },
        { p: "¿En qué huerto oró Jesús la noche antes de ser arrestado?", o: ["Edén", "Getsemaní", "Sinaí", "Monte de los Olivos"], c: 1 },
        { p: "¿Qué acto de humildad hizo Jesús con sus discípulos en la última cena?", o: ["Lavó sus pies", "Les dio dinero", "Los ungió con aceite", "Los bautizó"], c: 0 },
        { p: "¿Qué sucedió al tercer día de la muerte de Jesús?", o: ["Fue llevado al cielo", "Resucitó", "Apareció en Roma", "Se durmió"], c: 1 },
        { p: "¿A quién se le apareció Jesús primero tras resucitar?", o: ["A Pedro", "A María Magdalena", "A su madre María", "A Juan"], c: 1 },
        { p: "¿Desde qué monte ascendió Jesús al cielo?", o: ["Monte Sinaí", "Monte de los Olivos", "Monte Carmelo", "Monte Nebo"], c: 1 },
        { p: "¿Qué le dijo Jesús a la mujer samaritana junto al pozo?", o: ["Que le diera de comer", "Que le diera de beber agua viva", "Que se fuera a su casa", "Que pagara un impuesto"], c: 1 },
        { p: "¿Cómo sanó Jesús a un paralítico bajado por el techo?", o: ["Tocando su mano", "Perdonando sus pecados y diciéndole que se levante", "Echándole agua", "Con una oración a distancia"], c: 1 },
        { p: "¿A qué hija de líder religioso resucitó Jesús diciendo 'talita cumi'?", o: ["La hija de Jairo", "La hija de Faraón", "La hija de Herodes", "La hija de Pilato"], c: 0 },
        { p: "¿Qué parábola contó Jesús sobre un hijo que se fue de casa y gastó su dinero?", o: ["El buen samaritano", "El hijo pródigo", "El sembrador", "La oveja perdida"], c: 1 },
        { p: "¿Qué parábola enseña a amar al prójimo sin importar quién sea?", o: ["El hijo pródigo", "El buen samaritano", "Los talentos", "Las diez vírgenes"], c: 1 },
        { p: "¿Cómo calmó Jesús una gran tempestad en el mar?", o: ["Nadando hacia la orilla", "Ordenando al viento y al mar con autoridad", "Pidiendo que remaran más rápido", "Haciendo un sacrificio"], c: 1 },
        { p: "¿A qué hora del día se oscureció la tierra cuando Jesús murió en la cruz?", o: ["Desde la medianoche", "Desde la hora sexta hasta la novena", "Al amanecer", "Toda la noche"], c: 1 },
        { p: "¿Quién prestó su sepulcro nuevo para enterrar el cuerpo de Jesús?", o: ["José de Arimatea", "Nicodemo", "Simón de Cirene", "Cayafas"], c: 0 },
        { p: "¿Quién ayudó a Jesús a cargar la cruz camino al Calvario?", o: ["Juan", "Simón de Cirene", "Pedro", "Barrabás"], c: 1 },
        { p: "¿Qué criminal soltó la multitud en lugar de Jesús?", o: ["Barrabás", "Dimas", "Gestas", "Judas"], c: 0 },
        { p: "¿Qué nombre recibe el sermón más famoso de Jesús en el monte?", o: ["Sermón del Monte", "Sermón del Templo", "Sermón del Desierto", "Sermón de la llanura"], c: 0 },
        { p: "¿Qué pedía Jesús en sus enseñanzas sobre los enemigos?", o: ["Castigarlos", "Ignorarlos", "Amarles y orar por ellos", "Reclamar justicia"], c: 2 },
        { p: "¿Quién reconoció a Jesús como el Mesías guiado por el Espíritu en el templo de niño?", o: ["Simeón y Ana", "Zacarías y Elisabet", "José y María", "Herodes y los magos"], c: 0 },
        { p: "¿Qué le respondió Jesús a Satanás cuando fue tentado en el desierto?", o: ["Apártate de mí", "Escrito está...", "No te tengo miedo", "Dios te juzgará"], c: 1 },
        { p: "¿Cuántos días ayunó Jesús en el desierto?", o: ["7 días", "40 días", "3 días", "12 días"], c: 1 },
        { p: "¿Qué hizo Jesús en las bodas de Caná?", o: ["Predicó un sermón", "Convirtió el agua en vino", "Multiplicó la comida", "Sanó al novio"], c: 1 },
        { p: "¿A qué estanque acudió Jesús para sanar a un hombre que llevaba 38 años enfermo?", o: ["Betesda", "Siloé", "Cedrón", "Gichón"], c: 0 },
        { p: "¿A qué ciego mandó Jesús a lavarse al estanque de Siloé?", o: ["A Bartimeo", "Al ciego de nacimiento", "A un leproso", "A un fariseo"], c: 1 },
        { p: "¿Cómo se llamaba el fariseo principal que habló con Jesús sobre nacer de nuevo?", o: ["Gamaliel", "Nicodemo", "Anás", "Caifás"], c: 1 },
        { p: "¿Qué dijo Jesús que era Él respecto al camino?", o: ["Yo soy el camino, la verdad y la vida", "Yo soy la puerta de las ovejas", "Yo soy la luz del mundo", "Yo soy el buen pastor"], c: 0 },
        { p: "¿Qué dijo Jesús ser comparándose con las ovejas?", o: ["El buen pastor", "El cordero pascual", "El rey de reyes", "El guía fiel"], c: 0 },
        { p: "¿Qué ilustración usó Jesús sobre la vid verdadera?", o: ["Yo soy la vid, vosotros los pámpanos", "Yo soy el sembrador y vosotros la tierra", "Yo soy el árbol de la vida", "Yo soy el trigo limpio"], c: 0 },
        { p: "¿Qué enseñó Jesús sobre el pan de vida?", o: ["El que a mí viene no tendrá hambre", "El pan material es sagrado", "Hay que repartir trigo", "Ayunar es mejor que comer"], c: 0 },
        { p: "¿A qué ciudad se dirigían los dos discípulos cuando Jesús se les apareció resucitado sin que le reconocieran?", o: ["Jericó", "Emaús", "Nazaret", "Betania"], c: 1 },
        { p: "¿Qué le preguntó Jesús a Pedro tres veces junto al lago de Galilea?", o: ["¿Me amas?", "¿Me traicionaste?", "¿Me seguirás?", "¿Tienes hambre?"], c: 0 },
        { p: "¿Qué profetizó Jesús sobre la destrucción de Jerusalén?", o: ["Que no quedaría piedra sobre piedra", "Que sería quemada por fuego del cielo", "Que se hundiría en el mar", "Que nadie viviría allí jamás"], c: 0 },
        { p: "¿Cómo describió Jesús su segunda venida?", o: ["Como ladrón en la noche / con poder y gran gloria", "En secreto por un desierto", "En un eclipse solar permanente", "Con un terremoto mundial silencioso"], c: 0 },
        { p: "¿Qué mandamiento nuevo dio Jesús a sus discípulos?", o: ["Que os améis unos a otros", "Que guardéis el sábado", "Que paguéis tributo", "Que ayunéis cada semana"], c: 0 },
        { p: "¿Qué consolador prometió Jesús enviar tras su partida?", o: ["El Espíritu Santo", "Un ejército de ángeles", "A Moisés y Elías", "Nuevos profetas"], c: 0 },
        { p: "¿Cuál fue la última gran orden de Jesús antes de subir al cielo?", o: ["Id y haced discípulos a todas las naciones", "Construyan templos grandes", "Guarden silencio sobre mí", "Reúnanse solo en Jerusalén"], c: 0 },
        { p: "¿Qué dijo Jesús acerca de los niños?", o: ["Dejad a los niños venir a mí", "Que aprendan la ley primero", "Que no molesten a los maestros", "Que guarden silencio"], c: 0 },
        { p: "¿Qué opinó Jesús sobre la ofrenda de la viuda pobre?", o: ["Dio más que todos porque dio todo lo que tenía", "Era muy poco para aceptarse", "Debía juntar más para dar", "No tenía valor real"], c: 0 },
        { p: "¿A quiénes comparó Jesús con edificadores en la roca y en la arena?", o: ["A los que oyen sus palabras y las hacen vs los que no", "A los ricos y a los pobres", "A los fariseos y a los cobradores", "A los padres y a los hijos"], c: 0 },
        { p: "¿Qué dijo Jesús sobre el sábado?", o: ["El sábado fue hecho por causa del hombre", "El sábado no debe usarse para sanar", "El sábado es solo para dormir", "El sábado se abolió por completo"], c: 0 },
        { p: "¿Cómo respondió Jesús ante la mujer sorprendida en adulterio?", o: ["El que esté sin pecado arroje la piedra primera", "Que sea apedreada según la ley", "Que pague una multa", "Que sea expulsada del pueblo"], c: 0 },
        { p: "¿Qué hizo Jesús al entrar al templo y ver que vendían cosas?", o: ["Expulsó a los vendedores y cambistas", "Compró palomas para ofrecer", "Felicitó el comercio local", "Ignoró la situación"], c: 0 },
        { p: "¿Qué enseñó Jesús acerca de la oración en el Sermón del Monte?", o: ["Orad en vuestro aposento a vuestro Padre en secreto", "Griten fuerte en las plazas", "Repitan palabras sin sentido", "Oren solo de rodillas"], c: 0 },
        { p: "¿Qué oración modelo enseñó Jesús a sus discípulos?", o: ["El Padre Nuestro", "El Credo", "La oración de Jabes", "El Salmo 23"], c: 0 },
        { p: "¿Qué dijo Jesús sobre las riquezas en la tierra?", o: ["No os hagáis tesoros en la tierra", "Acumulen todo lo que puedan", "Las riquezas salvan el alma", "El dinero es el único fin"], c: 0 },
        { p: "¿Quién subió a un sicómoro para ver pasar a Jesús?", o: ["Zaqueo", "Mateo", "Leví", "Bartimeo"], c: 0 },
        { p: "¿Qué hizo Jesús en Betania antes de la fiesta de pascua con un perfume costoso?", o: ["Fue ungido por María de Betania", "Vendió el perfume para los pobres", "Regaló el frasco a Judas", "Lo derramó en el suelo"], c: 0 },
        { p: "¿Cómo entró Jesús triunfalmente a Jerusalén?", o: ["Montado en un pollino de asna", "En un carro de caballos", "A pie con una corona de oro", "Llevado en hombros"], c: 0 },
        { p: "¿Qué maldijo Jesús porque no tenía frutos sino solo hojas?", o: ["Una higuera", "Un olivo", "Una vid", "Un almendro"], c: 0 },
        { p: "¿Qué respondió Jesús al ser interrogado por Poncio Pilato sobre si era Rey?", o: ["Tú lo dices / Mi reino no es de este mundo", "No soy rey de nada", "Soy rey de Roma y Judea", "Prefiero callar para siempre"], c: 0 },
        { p: "¿Qué título colocaron sobre la cruz de Jesús en tres idiomas?", o: ["Jesús Nazareno, Rey de los Judíos", "El gran profeta de Galilea", "El salvador del mundo entero", "Hombre condenado por sedición"], c: 0 },
        { p: "¿Cuáles fueron unas de las últimas palabras de Jesús en la cruz antes de expirar?", o: ["Padre, en tus manos encomiendo mi espíritu", "Sálvate a ti mismo", "Todo ha terminado mal", "No sufran por mí"], c: 0 },
        { p: "¿Qué milagro ocurrió en el velo del templo al morir Jesús?", o: ["Se rasgó en dos de arriba a abajo", "Se volvió de color oro", "Se quemó por completo", "Se hizo de piedra dura"], c: 0 },
        { p: "¿Qué dijeron los soldados romanos al ver los eventos de la muerte de Jesús?", o: ["Verdaderamente este era Hijo de Dios", "Era solo un impostor más", "Cumplimos con nuestro trabajo", "Nadie debió morir así"], c: 0 },
        { p: "¿A qué hora resucitó Jesús según los relatos evangélicos?", o: ["Muy de mañana, el primer día de la semana", "A la medianoche del sábado", "Al atardecer del lunes", "A mediodía"], c: 0 },
        { p: "¿Qué hacían los guardias que cuidaban la tumba de Jesús al ver al ángel?", o: ["Temblaron y se quedaron como muertos", "Atacaron al ángel con espadas", "huyeron nadando al mar", "Cantaron alabanzas"], c: 0 },
        { p: "¿Qué mentira inventaron los principales sacerdotes sobre el cuerpo de Jesús?", o: ["Que sus discípulos lo robaron de noche durmiendo ellos", "Que se convirtió en espíritu", "Que fue trasladado a Galilea", "Que nunca existió"], c: 0 },
        { p: "¿Cómo reconoció Tomás a Jesús resucitado?", o: ["Al ver y tocar las marcas de los clavos y su costado", "Por su voz al gritar de lejos", "Porque vestía ropas reales", "Por una carta que le entregó"], c: 0 },
        { p: "¿Qué cantidad de peces pescaron milagrosamente los discípulos tras la resurrección en el lago?", o: ["153 grandes peces", "100 pescados exactos", "Una red llena sin contar", "12 peces grandes"], c: 0 },
        { p: "¿Qué le encargó Jesús tres veces a Simón Pedro tras su resurrección?", o: ["Apacienta mis ovejas / mis corderos", "Construye una gran catedral", "Vete a predicar a Roma", "Consigue oro para la iglesia"], c: 0 },
        { p: "¿Qué promesa especial dio Jesús a los que creen antes de ascender?", o: ["He aquí yo estoy con vosotros todos los días", "Nunca más tendrán problemas físicos", "Serán reyes en la tierra", "Tendrán riquezas materiales"], c: 0 },
        { p: "¿Qué festividad esperaban los discípulos en Jerusalén por mandato de Jesús tras su partida?", o: ["La promesa del Espíritu Santo (Pentecostés)", "La fiesta de las Cabañas", "La pascua judía anual", "El año del jubileo"], c: 0 },
        { p: "¿Cómo se llama la última carta o libro del Nuevo Testamento revelado por visión a Juan?", o: ["Apocalipsis o Revelación", "Epístola final", "Cartas celestiales", "Profecías de Patmos"], c: 0 },
        { p: "¿Qué frase repite Jesús al final del libro de Apocalipsis sobre su venida?", o: ["Cierto, vengo en breve. Amén", "Tardaré mucho tiempo", "No volveré más a la tierra", "Busquen mi reino en secreto"], c: 0 },
        { p: "¿Quién bautizó a Jesús en el río Jordán?", o: ["Juan el Bautista", "Pedro", "Santiago", "El profeta Elías"], c: 0 },
        { p: "¿En qué pueblo realizó Jesús su primer milagro convirtiendo agua en vino?", o: ["Caná de Galilea", "Belén", "Cafarnaúm", "Betania"], c: 0 },
        { p: "¿Qué categoría de personas buscó sanar principalmente Jesús en su ministerio terrenal?", o: ["A los enfermos, quebrantados y perdidos", "Solo a los gobernantes romanos", "Unicamente a los sacerdotes ricos", "A los filósofos griegos"], c: 0 },
        { p: "¿Qué dijo Jesús sobre el templo de su cuerpo?", o: ["Destruid este templo, y en tres días lo levantaré", "Este templo durará para siempre", "Mi cuerpo es un palacio de oro", "Nadie puede tocar mi templo"], c: 0 },
        { p: "¿A qué leproso sanó Jesús junto con otros nueve que no volvieron a agradecer?", o: ["A uno de los diez leprosos samaritanos", "A Naamán el sirio", "A un sacerdote de Jerusalén", "A un mendigo de Jericó"], c: 0 },
        { p: "¿Qué le respondió Jesús a Marta cuando su hermano Lázaro murió?", o: ["Yo soy la resurrección y la vida", "Tu hermano ya no importa", "Llorar es prohibido", "Resucitará dentro de mil años"], c: 0 },
        { p: "¿Qué enseñanza dejó Jesús sobre dar limosna?", o: ["No sepa tu izquierda lo que hace tu derecha", "Anúncialo con trompetas en las calles", "Dalo solo si te sobra mucho", "Cobra intereses por ello"], c: 0 },
        { p: "¿Cómo calificó Jesús la fe de un centurión romano?", o: ["No he hallado gran fe en Israel", "Una fe débil pero aceptable", "Fe basada en superstición", "Inexistente por ser extranjero"], c: 0 },
        { p: "¿Qué hizo Jesús cuando los discípulos discutían sobre quién era el mayor?", o: ["Puso a un niño en medio y dijo que el menor es el mayor", "Eligió al más fuerte como líder", "Les quitó sus túnicas", "Se enojó y se fue solo"], c: 0 },
        { p: "¿Qué respondió Jesús al joven rico que preguntó qué hacer para tener vida eterna?", o: ["Vende todo lo que tienes, dalo a pobres y sígueme", "Guarda silencio y medita", "Construye un templo grande", "Paga impuestos al templo"], c: 0 },
        { p: "¿Qué opinó Jesús acerca del pago de impuestos al César?", o: ["Dad al César lo que es del César y a Dios lo que es de Dios", "No paguen nada a los romanos", "El dinero pertenece al templo", "Roben a los cobradores"], c: 0 },
        { p: "¿Cómo sanó Jesús a los diez leprosos?", o: ["Les dijo: Id, mostraos a los sacerdotes, y quedaron limpios", "Los tocó uno por uno", "Les dio una poción mágica", "Los mandó al río Jordán"], c: 0 },
        { p: "¿Qué enseñanza dejó Jesús sobre el ayuno?", o: ["No seáis austeros como los hipócritas, unge tu cabeza y lava tu rostro", "Griten de dolor al ayunar", "Hagan ayuno solo de noche", "No ayunen nunca"], c: 0 },
        { p: "¿Qué dijo Jesús sobre la luz y la lámpara?", o: ["Nadie enciende una luz para ponerla debajo de un almud", "La luz debe esconderse de noche", "Las lámparas son solo decorativas", "Apaguen las luces para dormir"], c: 0 },
        { p: "¿Qué dijo Jesús sobre juzgar a los demás?", o: ["No juzguéis, para que no seáis juzgados", "Juzguen a todos sin piedad", "Solo los sacerdotes pueden juzgar", "Juzguen por las apariencias"], c: 0 },
        { p: "¿Qué dijo Jesús acerca de pedir, buscar y llamar?", o: ["Pedid, y se os dará; buscad, y hallaréis", "Pidan riquezas materiales grandes", "Llamen muchas veces sin fe", "Nadie responderá a sus ruegos"], c: 0 },
        { p: "¿A qué comparó Jesús a los que escuchan su palabra y la ponen por obra?", o: ["A un hombre prudente que edificó su casa sobre la roca", "A un tonto sin hogar", "A un rey con castillo de arena", "A un mercader rico"], c: 0 },
        { p: "¿Cuál fue la reacción de la gente al escuchar las enseñanzas de Jesús?", o: ["Se admiraban de su doctrina, porque les enseñaba como quien tiene autoridad", "Se burlaban de su acento", "No entendían nada de lo que decía", "Se dormían en las reuniones"], c: 0 },
        { p: "¿Qué dijo Jesús acerca de los falsos profetas?", o: ["Por sus frutos los conoceréis", "Por sus túnicas los identificaréis", "Nadie puede reconocer a un falso profeta", "Tienen marcas en la frente"], c: 0 },
        { p: "¿Quién era la madre terrenal de Jesús?", o: ["María", "Marta", "Isabel", "María Magdalena"], c: 0 }
    ],
    "Antiguo Testamento": [
        { p: "¿Quién construyó el arca para salvar a su familia y animales?", o: ["Moisés", "Noé", "Abraham", "David"], c: 1 },
        { p: "¿Quién derrotó al gigante filisteo Goliat con una honda?", o: ["Saúl", "Salomón", "David", "Sansón"], c: 2 },
        { p: "¿Cuántas plagas envió Dios sobre la tierra de Egipto?", o: ["7", "10", "12", "40"], c: 1 },
        { p: "¿Qué profeta fue tragado por un gran pez tras desobedecer a Dios?", o: ["Job", "Jonás", "Moisés", "Daniel"], c: 1 },
        { p: "¿Quién fue arrojado al foso de los leones por orar a Dios?", o: ["José", "David", "Daniel", "Ezequiel"], c: 2 },
        { p: "¿Cómo se llamaba el primer hombre creado por Dios?", o: ["Abel", "Set", "Adán", "Enoc"], c: 2 },
        { p: "¿Qué patriarca tenía una túnica de muchos colores regalada por su padre?", o: ["José", "Benjamín", "Jacob", "Esaú"], c: 0 },
        { p: "¿A qué líder le entregó Dios las tablas de los 10 mandamientos?", o: ["Moisés", "Josué", "Abraham", "Elías"], c: 0 },
        { p: "¿En qué monte se le entregaron los 10 mandamientos a Israel?", o: ["Monte Sinaí", "Monte Gólgota", "Monte Carmelo", "Monte Ararat"], c: 0 },
        { p: "¿Qué líder levantó su vara para abrir el Mar Rojo?", o: ["Josué", "Moisés", "Aarón", "David"], c: 1 },
        { p: "¿Quién dirigió al pueblo de Israel a derribar los muros de Jericó con trompetas?", o: ["Sansón", "Gedeón", "Josué", "Caleb"], c: 2 },
        { p: "¿Qué juez fuerte perdió su fuerza sobrenatural al cortarle el cabello?", o: ["David", "Sansón", "Salomón", "Saúl"], c: 1 },
        { p: "¿Quién fue considerado el rey más sabio de la historia de Israel?", o: ["David", "Salomón", "Ezequías", "Josías"], c: 1 },
        { p: "¿Qué señal puso Dios en el cielo como pacto de no destruir la tierra con agua otra vez?", o: ["Una estrella brillante", "Un arcoíris", "Una gran nube", "Un cometa"], c: 1 },
        { p: "¿A qué patriarca le pidió Dios que ofreciera a su hijo Isaac en sacrificio?", o: ["Jacob", "Abraham", "Lot", "Noé"], c: 1 },
        { p: "¿Cómo se llamaba la esposa fiel de Abraham?", o: ["Rebeca", "Raquel", "Sara", "Rut"], c: 2 },
        { p: "¿A qué personaje bíblico se le conoce como el hombre más paciente en medio del sufrimiento?", o: ["Job", "Moisés", "David", "Isaías"], c: 0 },
        { p: "¿Quién fue ungido como el primer rey de Israel a pesar de luego desobedecer?", o: ["David", "Salomón", "Saúl", "Samuel"], c: 2 },
        { p: "¿De qué árbol se le prohibió comer a Adán y Eva en el Edén?", o: ["Del árbol de la vida", "Del árbol del conocimiento del bien y del mal", "De la higuera", "Del olivo"], c: 1 },
        { p: "¿Quién interpretó los sueños del Faraón en Egipto y llegó a ser gobernador?", o: ["Moisés", "José", "Daniel", "Jacob"], c: 1 },
        { p: "¿Cómo se llamaba el hermano gemelo de Jacob que vendió su primogenitura por un plato de lentejas?", o: ["Esaú", "Labán", "Ismael", "Isaac"], c: 0 },
        { p: "¿Quién fue la madre de Samuel, quien oró fervientemente en el templo pidiendo un hijo?", o: ["Ana", "Penina", "Rut", "Noemí"], c: 0 },
        { p: "¿Qué profeta ascendió al cielo en un carro de fuego?", o: ["Elías", "Eliseo", "Isaías", "Jeremías"], c: 0 },
        { p: "¿Qué profeta sucedió a Elías y recibió su doble porción de espíritu al caer su manto?", o: ["Eliseo", "Amós", "Oseas", "Jonás"], c: 0 },
        { p: "¿Cómo se llamaba la joven moabita que fue fiel a su suegra Noemí y antepasada del rey David?", o: ["Rut", "Ester", "Orfa", "Abigail"], c: 0 },
        { p: "¿Qué reina judía arriesgó su vida para salvar a su pueblo de la masacre decretada por Amán?", o: ["Ester", "Vashti", "Jezabel", "Dalila"], c: 0 },
        { p: "¿Quién fue vendido por sus hermanos envidiosos a una caravana de madianitas?", o: ["José", "Benjamín", "Rubén", "Judá"], c: 0 },
        { p: "¿Qué nombre le puso Dios a Jacob tras luchar con el ángel en Peniel?", o: ["Israel", "Abraham", "Isaac", "Efraín"], c: 0 },
        { p: "¿Cómo se llamaba el monte donde Elías desafió a los profetas de Baal?", o: ["Monte Carmelo", "Monte Sinaí", "Monte Nebo", "Monte de los Olivos"], c: 0 },
        { p: "¿Qué rey de Babilonia conquistó Jerusalén y se llevó cautivos a los israelitas?", o: ["Nabucodonosor", "Ciro", "Darío", "Belsasar"], c: 0 },
        { p: "¿Qué jóvenes amigos de Daniel no se quisieron doblar ante la estatua de oro y sobrevivieron al horno de fuego?", o: ["Sadrac, Mesac y Abed-nego", "Pedro, Jacob y Juan", "Moisés, Aarón y Hur", "Josué y Caleb"], c: 0 },
        { p: "¿Qué vio Jacob en su sueño de una escalera que llegaba hasta el cielo?", o: ["Ángeles de Dios que subían y bajaban por ella", "A su hermano Esaú persiguiéndole", "A Abraham esperándole", "Unas gavillas de trigo doradas"], c: 0 },
        { p: "¿Cómo se llamaba el padre de Abraham?", o: ["Taré", "Noé", "Eber", "Naor"], c: 0 },
        { p: "¿Qué profeta llorón escribió el libro de Lamentaciones y profetizó la caída de Jerusalén?", o: ["Jeremías", "Ezequiel", "Daniel", "Isaías"], c: 0 },
        { p: "¿Qué profeta vio la visión de un valle de huesos secos que cobraron vida?", o: ["Ezequiel", "Isaías", "Amós", "Miqueas"], c: 0 },
        { p: "¿Qué rey mandó a escribir los Proverbios y construyó el primer gran templo en Jerusalén?", o: ["Salomón", "David", "Ezequías", "Josías"], c: 0 },
        { p: "¿Cuál fue el castigo de la mujer de Lot por mirar hacia atrás al huir de Sodoma?", o: ["Se convirtió en estatua de sal", "Se quedó ciega para siempre", "Fue tragada por la tierra", "Se perdió en el desierto"], c: 0 },
        { p: "¿Cómo se llamaban los dos hijos mayores de Noé además de Cam?", o: ["Sem y Jafet", "Abraham y Lot", "Moisés y Aarón", "Isaac y Jacob"], c: 0 },
        { p: "¿Qué instrumento musical tocaba el rey David para calmar al rey Saúl?", o: ["El arpa", "La trompeta", "El pandero", "La flauta"], c: 0 },
        { p: "¿Quién era el general del ejército sirio que fue sanado de lepra bañándose siete veces en el río Jordán?", o: ["Naamán", "Sisera", "Abner", "Joab"], c: 0 },
        { p: "¿Qué líder militar israelí le pidió a Dios que el sol se detuviera en Gabaón?", o: ["Josué", "Gedeón", "Otoniel", "Barac"], c: 0 },
        { p: "¿Cómo se llamaba la madre del profeta Samuel?", o: ["Ana", "Abigail", "Mical", "Betsabé"], c: 0 },
        { p: "¿Qué personaje del Antiguo Testamento fue sacado de las aguas del río por la hija del Faraón?", o: ["Moisés", "José", "Aarón", "Gedeón"], c: 0 },
        { p: "¿Cómo se llamaba la hermana de Moisés que cantó y tocó el pandero tras cruzar el Mar Rojo?", o: ["María (Miriam)", "Séfora", "Jocabed", "Abigail"], c: 0 },
        { p: "¿Cuál fue la plaga número diez y última enviada sobre Egipto?", o: ["La muerte de los primogénitos", "Tinieblas densas", "Langostas devoradoras", "Granizo con fuego"], c: 0 },
        { p: "¿Qué marca debían poner los israelitas en sus puertas la noche de la Pascua en Egipto?", o: ["Sangre de cordero en los postes y dinteles", "Una rama de olivo verde", "Marcas de aceite de oliva", "Polvo del desierto"], c: 0 },
        { p: "¿Cómo alimentó Dios a los israelitas en el desierto durante 40 años?", o: ["Con maná del cielo y codornices", "Con uvas gigantes y pan", "Con frutos silvestres de los árboles", "Con agua y dátiles"], c: 0 },
        { p: "¿Qué milagro hizo Dios con la vara de Aarón frente al Faraón y contra otras varas?", o: ["Se convirtió en serpiente y devoró las demás", "Echó fuego y quemó el palacio", "Floreció con almendras de oro", "Se hizo de piedra dura"], c: 0 },
        { p: "¿Qué animal habló con el profeta Balaam para reprender su insensatez?", o: ["Una asna", "Un león", "Un cordero", "Una paloma"], c: 0 },
        { p: "¿Cómo murió Sansón al final de su vida destruyendo el templo de los filisteos?", o: ["Derribando las columnas principales del edificio", "Cayendo de un caballo en batalla", "Enfermando de fiebre alta", "Envenenado por sus enemigos"], c: 0 },
        { p: "¿Qué juez de Israel venció a un gran ejército enemigo usando solo 300 hombres con cántaros y antorchas?", o: ["Gedeón", "Jefté", "Barac", "Samson"], c: 0 },
        { p: "¿Qué rey filisteo trató de engañar a Sansón a través de Dalila?", o: ["Los príncipes de los filisteos", "Aquis de Gat", "Goliat de Get", "Agag de Amalec"], c: 0 },
        { p: "¿Quién era el amigo fiel de David que lo protegió de la furia de su padre Saúl?", o: ["Jonatán", "Abner", "Joab", "Natán"], c: 0 },
        { p: "¿Qué profeta confrontó al rey David tras su pecado con Betsabé usando la historia de una ovejita?", o: ["Natán", "Gad", "Samuel", "Elías"], c: 0 },
        { p: "¿Cómo se llamaba el hijo que tuvieron David y Betsabé que luego llegó a ser rey sabio?", o: ["Salomón", "Absalón", "Amnón", "Natán"], c: 0 },
        { p: "¿Qué hijo de David se rebeló contra él y trató de usurparle el trono montado en una mula?", o: ["Absalón", "Adonías", "Salomón", "Amnón"], c: 0 },
        { p: "¿Qué reina de Saba visitó a Salomón al escuchar de su gran sabiduría?", o: ["La reina de Saba", "La reina de Candace", "La reina Vashti", "La reina Jezabel"], c: 0 },
        { p: "¿Cómo se dividió el reino de Israel tras la muerte del rey Salomón?", o: ["En dos reinos: Israel al norte y Judá al sur", "En doce reinos independientes", "Fue conquistado por los persas inmediatamente", "Quedó gobernado por jueces"], c: 0 },
        { p: "¿Qué malvada reina promovió el culto al dios Baal en Israel y persiguió a los profetas de Dios?", o: ["Jezabel", "Atalía", "Vasti", "Maaca"], c: 0 },
        { p: "¿Cómo murió la reina malvada Jezabel en Jezreel?", o: ["Fue arrojada por una ventana y devorada por perros", "Murió quemada en su propio palacio", "Fue envenenada por sus siervos", "Ahogada en un río caudaloso"], c: 0 },
        { p: "¿Qué rey piadoso de Judá encontró el libro de la ley escondido en el templo al repararlo?", o: ["Josías", "Ezequías", "Asa", "Josafat"], c: 0 },
        { p: "¿Qué rey de Judá vio su vida prolongada por 15 años más tras orar enfermo con lágrimas?", o: ["Ezequías", "Acaz", "Manasés", " Jotam"], c: 0 },
        { p: "¿Qué profeta predijo el nacimiento virginal del Mesías escribiendo 'He aquí que la virgen concebirá y dará a luz un hijo'?", o: ["Isaías", "Jeremías", "Ezequiel", "Daniel"], c: 0 },
        { p: "¿Dónde nació el profeta Samuel y dónde sirvió bajo el sumo sacerdote Elí?", o: ["En el templo de Silo", "En Jerusalén", "En Belén", "En Nazaret"], c: 0 },
        { p: "¿Qué oficio tenía el profeta Amós antes de ser llamado por Dios a profetizar?", o: ["Boyero y pastor recolector de higos silvestres", "Pescador del mar", "Sacerdote del templo", "Carpintero de aldea"], c: 0 },
        { p: "¿Qué libro del Antiguo Testamento es una colección de cantos, oraciones y alabanzas de Israel?", o: ["El libro de los Salmos", "Proverbios", "Eclesiastés", "Cantar de los Cantares"], c: 0 },
        { p: "¿Qué libro bíblico fue escrito por Salomón enfocándose en que todo bajo el sol es vanidad sin Dios?", o: ["Eclesiastés", "Proverbios", "Job", "Lamentaciones"], c: 0 },
        { p: "¿Qué libro poético describe el amor con lenguaje nupcial y alegórico dentro de la sabiduría?", o: ["Cantar de los Cantares", "Rut", "Ester", "Lamentaciones"], c: 0 },
        { p: "¿Quién fue el padre de los doce patriarcas que dieron nombre a las tribus de Israel?", o: ["Jacob (Israel)", "Abraham", "Isaac", "José"], c: 0 },
        { p: "¿Cómo se llamaba la madre de José y Benjamín, la esposa amada de Jacob?", o: ["Raquel", "Lea", "Bilha", "Zilpa"], c: 0 },
        { p: "¿Cómo se llamaba la primera esposa de Jacob con quien se casó por engaño de su tío Labán?", o: ["Lea", "Raquel", "Milca", "Zilpa"], c: 0 },
        { p: "¿Qué patriarca vivió 969 años, siendo el hombre más longevo mencionado en la Biblia?", o: ["Matusalén", "Noé", "Adán", "Enoc"], c: 0 },
        { p: "¿Qué pasó con Enoc, el hombre que caminó fielmente con Dios?", o: ["Desapareció porque Dios se lo llevó sin ver muerte", "Murió a los mil años en paz", "Fue llevado al cielo en carro de fuego", "Fue trasladado a otra tierra lejana"], c: 0 },
        { p: "¿Qué rey persa firmó el decreto para que los judíos regresaran a reconstruir el templo de Jerusalén?", o: ["Ciro el Grande", "Artajerjes", "Darío", "Asuero"], c: 0 },
        { p: "¿Quién lideró la reconstrucción de los muros de Jerusalén en tiempo récord con la espada en una mano y la mezcla en la otra?", o: ["Nehemías", "Esdras", "Zorobabel", "Josué hijo de Josadac"], c: 0 },
        { p: "¿Quién fue el sacerdote y escriba que enseñó la ley al pueblo de Israel al regresar del cautiverio?", o: ["Esdras", "Nehemías", "Aco", "Zacarías"], c: 0 },
        { p: "¿Qué profeta menor escribió acerca de robarle a Dios los diezmos y ofrendas?", o: ["Malaquías", "Hageo", "Zacarías", "Sofonías"], c: 0 },
        { p: "¿Qué profeta fue mandado por Dios a casarse con una mujer infiel para ilustrar el amor de Dios por Israel?", o: ["Oseas", "Joel", "Amós", "Jonás"], c: 0 },
        { p: "¿Qué plaga de insectos describe el profeta Joel como juicio de Dios sobre la tierra?", o: ["Una invasión devastadora de langostas", "Mosquitos venenosos", "Abejas bravas", "Hormigas gigantes"], c: 0 },
        { p: "¿Qué profeta pastor de Tecoa denunció la injusticia social y la opresión de los pobres?", o: ["Amós", "Oseas", "Miqueas", "Nahúm"], c: 0 },
        { p: "¿Qué profeta declaró que el Mesías nacería en el pequeño pueblo de Belén Efrata?", o: ["Miqueas", "Isaías", "Jeremías", "Habacuc"], c: 0 },
        { p: "¿Contra qué ciudad profetizó Nahúm la destrucción total por su crueldad?", o: ["Nínive", "Babilonia", "Tiro", "Damasco"], c: 0 },
        { p: "¿Qué profeta le preguntó a Dios por qué permitía tanta maldad diciendo '¿hasta cuándo clamaré...?'?", o: ["Habacuc", "Sofonías", "Hageo", "Malaquías"], c: 0 },
        { p: "¿Qué profeta animó al pueblo a terminar de reconstruir el templo diciendo 'la gloria postrera será mayor que la primera'?", o: ["Hageo", "Zacarías", "Malaquías", "Joel"], c: 0 },
        { p: "¿Qué visión de caballos y jinetes tuvo el profeta Zacarías en sus mensajes proféticos?", o: ["Visiones nocturnas de consolación para Jerusalén", "Caballos para la guerra de los persas", "Animales salvajes del desierto", "Carros de fuego celestiales"], c: 0 },
        { p: "¿Cómo se llamaba el monte donde murió el líder Moisés sin poder entrar a la tierra prometida?", o: ["Monte Nebo", "Monte Sinaí", "Monte Carmelo", "Monte de los Olivos"], c: 0 },
        { p: "¿Quién guió al pueblo de Israel a cruzar el río Jordán en seco tras la muerte de Moisés?", o: ["Josué", "Caleb", "Eleazar", "Aarón"], c: 0 },
        { p: "¿Qué señal pusieron los espías en la ventana de Rahab para salvar a su familia en Jericó?", o: ["Un cordón de hilo rojo", "Una bandera blanca", "Una antorcha encendida", "Una rama de olivo"], c: 0 },
        { p: "¿Quién traicionó el escondite de Sansón revelando el secreto de su fuerza a los filisteos?", o: ["Dalila", "Una criada de Timnat", "Su propia madre", "Una reina extranjera"], c: 0 },
        { p: "¿Qué mujer valiente mató al general enemigo Sísara clavándole una estaca en la sien con un mazo?", o: ["Jael", "Débora", "Abigail", "Huldah"], c: 0 },
        { p: "¿Quién fue la jueza y profetisa que lideró a Israel junto a Barac en la batalla contra Canaán?", o: ["Débora", "Jael", "Miriam", "Ester"], c: 0 },
        { p: "¿Qué hizo el rey Saúl en desobediencia directa a Dios en la batalla contra los amalecitas?", o: ["Perdonó la vida al rey Agag y guardó lo mejor del ganado", "Huyó del campo de batalla cobardemente", "Destruyó todo sin consultar al sacerdote", "Ofreció un sacrificio prohibido"], c: 0 },
        { p: "¿Qué profeta ungió en secreto al joven pastor David en la casa de Isaí en Belén?", o: ["Samuel", "Natán", "Gad", "Elías"], c: 0 },
        { p: "¿Cómo reaccionó David cuando el profeta Natán le reprendió por su pecado?", o: ["Reconoció su pecado diciendo: Pequé contra Jehová", "Se enojó y echó al profeta", "Culpó a Betsabé de lo ocurrido", "Huyó al desierto a esconderse"], c: 0 },
        { p: "¿Qué libro del Antiguo Testamento relata la historia de un hombre rico que pierde todo, se queda en ruinas y luego Dios le restituye?", o: ["Libro de Job", "Proverbios", "Eclesiastés", "Salmos"], c: 0 },
        { p: "¿Qué animal gigante marino o monstruo acuático se menciona en el libro de Job y en los Salmos?", o: ["El Leviatán", "Un tiburón blanco gigante", "Una ballena azul", "Un cocodrilo del Nilo"], c: 0 },
        { p: "¿Qué criatura terrestre imponente se describe en Job comiendo hierba como buey?", o: ["El Behemot", "Un elefante salvaje", "Un rinoceronte", "Un hipopótamo gigante"], c: 0 },
        { p: "¿Cómo se llamaban los tres amigos de Job que fueron a consolarle pero terminaron discutiendo con él?", o: ["Elifaz, Bildad y Zofar", "Pedro, Pablo y Juan", "Sadrac, Mesac y Abed-nego", "Ciro, Darío y Artajerjes"], c: 0 },
        { p: "¿Quién fue el cuarto joven que habló con Job y le dio palabras de sabiduría al final de las discusiones?", o: ["Eliú hijo de Baraquel", "Abner", "Natán", "Ezequías"], c: 0 },
        { p: "¿Qué significa el nombre del profeta Emanuel profetizado por Isaías?", o: ["Dios con nosotros", "Dios es fuerte", "El salvador del mundo", "Rey de justicia"], c: 0 }
    ],
    "Nuevo Testamento": [
        { p: "¿Quién escribió la mayor cantidad de cartas o epístolas en el Nuevo Testamento?", o: ["Pedro", "Juan", "Pablo", "Santiago"], c: 2 },
        { p: "¿En qué isla se encontraba el apóstol Juan cuando escribió el libro de Apocalipsis?", o: ["Chipre", "Malta", "Patmos", "Creta"], c: 2 },
        { p: "¿Qué oficio tenía Mateo antes de convertirse en seguidor de Jesús?", o: ["Pescador", "Carpintero", "Cobrador de impuestos", "Médico"], c: 2 },
        { p: "¿Qué apóstol de Jesús era médico de profesión?", o: ["Lucas", "Marcos", "Juan", "Mateo"], c: 0 },
        { p: "¿En qué camino iba Saulo cuando quedó ciego por una gran luz celestial?", o: ["Camino a Emaús", "Camino a Damasco", "Camino a Jerusalén", "Camino a Jericó"], c: 1 },
        { p: "¿Qué discípulo fue elegido por sorteo para reemplazar a Judas Iscariote?", o: ["Matías", "Pablo", "Bernabé", "Timoteo"], c: 0 },
        { p: "¿Quién es considerado el primer mártir cristiano, apedreado por defender su fe?", o: ["Pedro", "Esteban", "Santiago", "Pablo"], c: 1 },
        { p: "¿En qué festividad judía descendió el Espíritu Santo sobre los creyentes en forma de lenguas de fuego?", o: ["Pascua", "Pentecostés", "Tabernáculos", "Purim"], c: 1 },
        { p: "¿Cuál es el último libro que compone el canon del Nuevo Testamento?", o: ["Judas", "Apocalipsis", "Hebreos", "3 Juan"], c: 1 },
        { p: "¿Cuántos evangelios canónicos narran la vida y obra de Jesús al inicio del Nuevo Testamento?", o: ["3", "4", "5", "12"], c: 1 },
        { p: "¿Quién bautizaba en el desierto vistiendo ropa de pelo de camello y comiendo langostas?", o: ["Juan el Bautista", "El profeta Elías", "Pedro", "Pablo"], c: 0 },
        { p: "¿Qué discípulo dudó inicialmente de la resurrección de Jesús hasta verle y tocarle?", o: ["Felipe", "Tomás", "Andrés", "Judas"], c: 1 },
        { p: "¿Qué fariseo principal acudió a hablar con Jesús en la oscuridad de la noche?", o: ["Caifás", "Nicodemo", "Gamaliel", "Pilato"], c: 1 },
        { p: "¿Quién era el gobernador romano que sentenció a Jesús a la crucifixión en Judea?", o: ["Herodes Antipas", "Poncio Pilato", "César Augusto", "Félix"], c: 1 },
        { p: "¿Qué libro histórico del Nuevo Testamento narra el nacimiento y expansión de la iglesia primitiva?", o: ["Romanos", "Hebreos", "Hechos de los Apóstoles", "Gálatas"], c: 2 },
        { p: "¿A qué mujer cristiana resucitó el apóstol Pedro en Jope, conocida por sus buenas obras?", o: ["Lidia", "Dorcas (Tabita)", "Priscila", "María la madre de Marcos"], c: 1 },
        { p: "¿Quién fue el primer compañero misionero del apóstol Pablo en sus primeros viajes?", o: ["Bernabé", "Tomás", "Juan Marcos", "Pedro"], c: 0 },
        { p: "¿Cómo se llamaba el ciego que clamaba pidiendo misericordia a la salida de Jericó?", o: ["Zaqueo", "Bartimeo", "Lázaro", "Jairo"], c: 1 },
        { p: "¿En qué ciudad fueron llamados los discípulos 'cristianos' por primera vez en la historia?", o: ["Jerusalén", "Antioquía", "Roma", "Éfeso"], c: 1 },
        { p: "¿Quién escribió el libro de los Hechos de los Apóstoles dirigido a Teófilo?", o: ["Pablo", "Lucas", "Pedro", "Juan"], c: 1 },
        { p: "¿Cómo se llamaba la mujer vendedora de púrpura en Filipos que hospedó a Pablo y Silas?", o: ["Lidia", "Priscila", "Febe", "Drusila"], c: 0 },
        { p: "¿Qué joven colaborador de Pablo en sus viajes era considerado por él como su hijo amado en la fe?", o: ["Timoteo", "Tito", "Bernabé", "Esteban"], c: 0 },
        { p: "¿Qué carta de Pablo habla detalladamente sobre el amor en el capítulo 13?", o: ["1 Corintios", "Romanos", "Gálatas", "Efesios"], c: 0 },
        { p: "¿Qué epístola paulina describe la Armadura de Dios completa para la batalla espiritual?", o: ["Efesios", "Filipenses", "Colosenses", "Tesalonicenses"], c: 0 },
        { p: "¿Qué apóstol escribió la carta corta dirigida a Filemón sobre el esclavo Onésimo?", o: ["Pablo", "Pedro", "Juan", "Santiago"], c: 0 },
        { p: "¿Cuál es el libro del Nuevo Testamento que explica cómo la fe sin obras es muerta?", o: ["Santiago", "Judas", "1 Pedro", "Hebreos"], c: 0 },
        { p: "¿Quién escribió la carta de los Hebreos explicando la superioridad del sacerdocio de Cristo?", o: ["Autor anónimo (atribuida a varios)", "El apóstol Pablo", "El apóstol Pedro", "El apóstol Juan"], c: 0 },
        { p: "¿Qué anciano líder de la iglesia escribió tres epístolas breves enfocadas en el amor fraterno y la verdad?", o: ["Juan el apóstol", "Pedro", "Santiago", "Bernabé"], c: 0 },
        { p: "¿Qué apóstol negó conocer a Jesús tres veces antes de que cantara el gallo?", o: ["Pedro", "Andrés", "Felipe", "Bartolomé"], c: 0 },
        { p: "¿Quién fue el recaudador de impuestos bajito que trepó a un árbol para ver a Jesús?", o: ["Zaqueo", "Mateo", "Leví", "Simón"], c: 0 },
        { p: "¿Qué diácono lleno del Espíritu Santo fue transportado por el Espíritu tras bautizar al etíope eunuco?", o: ["Felipe", "Esteban", "Prócoro", "Nicanor"], c: 0 },
        { p: "¿Cómo se llamaba la pareja de fabricantes de tiendas que instruyó a Apolos en Éfeso junto a Pablo?", o: ["Aquila y Priscila", "Ananías y Safira", "Felix y Drusila", "Herodes y Herodías"], c: 0 },
        { p: "¿Qué matrimonio mintió al apóstol Pedro sobre el dinero de una propiedad y murió instantáneamente?", o: ["Ananías y Safira", "Aquila y Priscila", "Zacarías y Elisabet", "Adán y Eva"], c: 0 },
        { p: "¿Qué profeta del Nuevo Testamento predijo una gran hambre en el tiempo del emperador Claudio?", o: ["Ágabo", "Simeón", "Ángel del Señor", "Bernabé"], c: 0 },
        { p: "¿Qué gobernador romano tembló al escuchar al apóstol Pablo predicar sobre la justicia y el juicio venidero?", o: ["Félix", "Festus", "Herodes Agripa", "Poncio Pilato"], c: 0 },
        { p: "¿Qué rey intentó impresionar a la gente vistiendo ropas reales y fue comido por gusanos por no dar gloria a Dios?", o: ["Herodes Agripa I", "Herodes el Grande", "Arquelao", "Filipo"], c: 0 },
        { p: "¿Qué apóstol fue hermano de Simón Pedro y pescador de Galilea?", o: ["Andrés", "Juan", "Santiago", "Mateo"], c: 0 },
        { p: "¿Quiénes eran los hijos de Zebedeo conocidos como los 'Hijos del Trueno'?", o: ["Jacobo y Juan", "Pedro y Andrés", "Felipe y Bartolomé", "Tomás y Mateo"], c: 0 },
        { p: "¿Qué evangelio destaca especialmente la humanidad y compasión de Jesús hacia los marginados y necesitados?", o: ["El evangelio según Lucas", "Mateo", "Marcos", "Juan"], c: 0 },
        { p: "¿Qué evangelio comienza con la famosa declaración 'En el principio era el Verbo...'?", o: ["El evangelio según Juan", "Mateo", "Marcos", "Lucas"], c: 0 },
        { p: "¿Qué evangelio es considerado el más corto y dinámico de los cuatro?", o: ["Marcos", "Mateo", "Lucas", "Juan"], c: 0 },
        { p: "¿Qué evangelio fue escrito originalmente pensando en una audiencia judía para mostrar que Jesús es el Mesías prometido?", o: ["Mateo", "Marcos", "Lucas", "Juan"], c: 0 },
        { p: "¿Qué apóstol escribió la advertencia de que el diablo anda como león rugiente buscando a quien devorar?", o: ["Pedro", "Pablo", "Juan", "Judas"], c: 0 },
        { p: "¿Qué hermano de Jesús escribió una carta práctica sobre el control de la lengua y la sabiduría celestial?", o: ["Santiago", "Judas", "José", "Simón"], c: 0 },
        { p: "¿Qué hermano de Jesús escribió una carta corta advirtiendo contra los falsos maestros infiltrados?", o: ["Judas", "Santiago", "José", "Matías"], c: 0 },
        { p: "¿Qué le ocurrió a Pablo y Silas cuando cantaban himnos a la medianoche en la cárcel de Filipos?", o: ["Un gran terremoto abrió las puertas y soltó las cadenas de todos", "Los guardias se convirtieron al instante", "El techo se abrió y huyeron volando", "El carcelero se enojó y los sacó"], c: 0 },
        { p: "¿Cómo reaccionó el carcelero de Filipos al ver las puertas abiertas tras el terremoto?", o: ["Iba a matarse, pero Pablo le detuvo y creyó en el Señor", "Huyó por miedo a las autoridades romanas", "Atacó a los presos con su espada", "Se desmayó del susto"], c: 0 },
        { p: "¿En qué ciudad griega predicó Pablo en el Areópago ante los filósofos epicúreos y estoicos?", o: ["Atenas", "Corinto", "Tesalónica", "Éfeso"], c: 0 },
        { p: "¿Qué diosa pagana adoraban los habitantes de Éfeso en un templo considerado una maravilla del mundo antiguo?", o: ["Diana (Artemisa)", "Atenea", "Afrodita", "Hera"], c: 0 },
        { p: "¿Qué platero causó un gran alboroto en Éfeso porque la predicación de Pablo afectaba su negocio de ídolos?", o: ["Demetrio", "Alejandro", "Himeneo", "Fileto"], c: 0 },
        { p: "¿Qué joven se durmió mientras Pablo predicaba largo rato en Troas, cayó desde un tercer piso y resucitó?", o: ["Eutico", "Tíquico", "Trófimo", "Erasto"], c: 0 },
        { p: "¿Qué profecía le dio el profeta Ágabo a Pablo en Cesarea respecto a su visita a Jerusalén?", o: ["Que los judíos lo atarían y entregarían a los gentiles", "Que sería nombrado rey de Judea", "Que viajaría libremente a España", "Que escaparía en un barco seguro"], c: 0 },
        { p: "¿Cómo se salvó la vida de todos los que viajaban en el barco con Pablo cuando naufragaron rumbo a Roma?", o: ["Todos nadaron o llegaron en maderas a la isla de Malta", "Un barco militar los rescató en alta mar", "El capitán logró atracar en puerto seguro", "Llegaron flotando milagrosamente sin esfuerzo"], c: 0 },
        { p: "¿Qué animal venenoso mordió la mano del apóstol Pablo en la isla de Malta sin hacerle ningún daño?", o: ["Una víbora", "Una serpiente marina", "Un escorpión negro", "Una araña gigante"], c: 0 },
        { p: "¿Cómo reaccionaron los nativos de Malta al ver que la serpiente no mató a Pablo?", o: ["Pensaron que era un dios", "Se asustaron y lo echaron de la isla", "Le pidieron dinero a cambio de paz", "Lo tomaron como un criminal peligroso"], c: 0 },
        { p: "¿En qué condiciones vivió el apóstol Pablo sus últimos días en Roma antes de su martirio?", o: ["En una casa alquilada bajo custodia militar con libertad relativa", "En una mazorca oscura y profunda sin luz", "Prisionero en el palacio del emperador César", "Exiliado en una isla desierta lejana"], c: 0 },
        { p: "¿Qué le pidió Pablo a Timoteo que le llevara urgentemente junto con sus pergaminos en su última carta?", o: ["Su capa que dejó en Troas", "Un poco de vino para su estómago", "Sandalias nuevas de cuero", "Dinero para pagar deudas"], c: 0 },
        { p: "¿Qué hermosa declaración hizo Pablo sobre su carrera al final de su vida en 2 Timoteo?", o: ["He peleado la buena batalla, he acabado la carrera, he guardado la fe", "He ganado muchas riquezas para el Señor", "He construido templos en todo el imperio", "He escrito muchos libros sagrados"], c: 0 },
        { p: "¿Cuál es el tema central del libro de Apocalipsis desde su primer versículo?", o: ["La revelación de Jesucristo", "El fin físico del planeta tierra", "La historia secreta de Roma", "El juicio final a los ángeles caídos"], c: 0 },
        { p: "¿Cuántas iglesias de Asia Menor reciben cartas directas de Jesús en los capítulos 2 y 3 de Apocalipsis?", o: ["Siete iglesias", "Tres iglesias", "Doce iglesias", "Diez iglesias"], c: 0 },
        { p: "¿Qué representan los candeleros de oro en las visiones iniciales del libro de Apocalipsis?", o: ["Las siete iglesias", "Los siete espíritus de Dios", "Los ángeles protectores", "Las trompetas del juicio"], c: 0 },
        { p: "¿Quién es digno de tomar el libro y abrir sus sellos en la visión celestial de Apocalipsis?", o: ["El Cordero que fue inmolado (Jesucristo)", "Un ángel poderoso con espada", "El profeta Moisés", "Los veinticuatro ancianos"], c: 0 },
        { p: "¿Qué se describe en Apocalipsis que sale al abrir los primeros cuatro sellos?", o: ["Los cuatro jinetes del apocalipsis", "Cuatro ángeles con copas de ira", "Terremotos y maremotos globales", "Truenos y relámpagos espantosos"], c: 0 },
        { p: "¿Cómo se describe la nueva Jerusalén que desciende del cielo al final de Apocalipsis?", o: ["Como una esposa ataviada para su marido, con oro y piedras preciosas", "Como un castillo fortificado militar", "Como una ciudad flotante de nubes blancas", "Como un templo de piedra antigua"], c: 0 },
        { p: "¿Qué afirmación final promete Jesús al cierre del libro de Apocalipsis en la Biblia?", o: ["¡Sí, vengo pronto!", "No volveré jamás", "El tiempo se ha detenido", "Guarden silencio hasta mi vuelta"], c: 0 },
        { p: "¿Quién fue el ángel que anunció a María que concebiría y daría a luz al Hijo de Dios?", o: ["El ángel Gabriel", "El ángel Miguel", "El arcángel Rafael", "Un ángel sin nombre"], c: 0 },
        { p: "¿A qué lugar huyeron José, María y el niño Jesús para escapar de la furia de Herodes?", o: ["A Egipto", "A Damasco", "A Babilonia", "A Tarso de Cilicia"], c: 0 },
        { p: "¿Qué sabios del oriente guiados por una estrella llegaron a adorar al niño Jesús llevándole regalos?", o: ["Unos magos", "Unos pastores de Belén", "Reyes sacerdotes de Roma", "Filósofos griegos"], c: 0 },
        { p: "¿Quiénes fueron los primeros en recibir la noticia del nacimiento de Jesús por parte de un ángel en los campos?", o: ["Unos pastores que velaban sus rebaños de noche", "Los sumos sacerdotes del templo", "Los escribas de Jerusalén", "Los guardias del palacio de Herodes"], c: 0 },
        { p: "¿Cómo se llamaban los padres del profeta Juan el Bautista?", o: ["Zacarías y Elisabet", "Joaquín y Ana", "José y María", "Simeón y Ana"], c: 0 },
        { p: "¿Qué le pasó temporalmente a Zacarías por dudar del mensaje del ángel sobre el nacimiento de su hijo?", o: ["Se quedó mudo hasta que nació el niño", "Se quedó ciego por completo", "Perdió la memoria de las Escrituras", "No pudo caminar por meses"], c: 0 },
        { p: "¿Qué anciano devoto en el templo tomó al niño Jesús en sus brazos y alabó a Dios diciendo que ya podía morir en paz?", o: ["Simeón", "Gamaliel", "Anás", "Caifás"], c: 0 },
        { p: "¿Cómo se llamaba la anciana profetisa que servía en el templo ayunando y orando cuando presentaron a Jesús de niño?", o: ["Ana", "Marta", "Salomé", "Juana"], c: 0 },
        { p: "¿Cuál fue el primer discípulo que llamó a su hermano Simón Pedro a seguir a Jesús diciendo 'Hemos hallado al Mesías'?", o: ["Andrés", "Juan", "Felipe", "Santiago"], c: 0 },
        { p: "¿A qué discípulo le dijo Jesús 'Antes que Felipe te llamase, cuando estabas debajo de la higuera, te vi'?", o: ["Nataneal (Bartolomé)", "Tomás", "Mateo", "Judas Tadeo"], c: 0 },
        { p: "¿Cómo se llamaba la mujer de Magdala de quien Jesús expulsó siete demonios?", o: ["María Magdalena", "Juana", "Susana", "Marta"], c: 0 },
        { p: "¿Qué hermanas hospedaban a Jesús en su casa en la aldea de Betania junto a su hermano Lázaro?", o: ["Marta y María", "Eunice y Loida", "Priscila y Lidia", "María y Salomé"], c: 0 },
        { p: "¿Qué le respondió Jesús a Marta cuando se preocupaba demasiado por los quehaceres del hogar?", o: ["María ha escogido la buena parte, la cual no le será quitada", "Ayúdala en la cocina inmediatamente", "Las tareas no importan para nada", "Prepara comida para todos los invitados"], c: 0 },
        { p: "¿Qué hizo una mujer pecadora con un frasco de alabastro lleno de perfume costoso sobre los pies de Jesús?", o: ["Los lavó con sus lágrimas y los ungió con perfume secándolos con sus cabellos", "Los rompió contra el suelo enfrente de los fariseos", "Se los regaló a Judas para venderlos", "Echó perfume en la cabeza de los invitados"], c: 0 },
        { p: "¿Cómo reaccionó Judas Iscariote ante el perfume costoso derramado por María antes de la cruz?", o: ["Se quejó diciendo que debió venderse para dar a los pobres (robándose él la bolsa)", "Felicitó el acto de amor sincero", "Guardó silencio por pena", "Se fue del lugar muy molesto"], c: 0 },
        { p: "¿Qué profecía cumplió Jesús al entrar montado en un pollino de asna a Jerusalén?", o: ["La profecía de Zacarías sobre el rey humilde montado en un asnillo", "La profecía de Isaías sobre el varón de dolores", "La profecía de Daniel sobre el hijo del hombre", "La profecía de Moisés sobre el gran libertador"], c: 0 },
        { p: "¿Qué gritaba la multitud jubilosa al recibir a Jesús en su entrada triunfal a Jerusalén?", o: ["¡Hosanna! ¡Bendito el que viene en el nombre del Señor!", "¡Crucifícalo! ¡Fuera de aquí!", "¡Salve al rey de los ejércitos romanos!", "¡Aleluya por el nuevo templo!"], c: 0 },
        { p: "¿Quiénes fueron los dos discípulos enviados por Jesús a buscar el pollino atado para su entrada a Jerusalén?", o: ["La Biblia no menciona los nombres exactos", "Pedro y Juan", "Santiago y Andrés", "Felipe y Tomás"], c: 0 },
        { p: "¿Qué enseñanza principal dejó Jesús al lavar los pies de sus discípulos en la última cena?", o: ["Ejemplo de amor y servicio mutuo: el mayor debe servir a los demás", "Que debían abrir un negocio de lavado", "Una regla ceremonial para entrar al templo", "Una purificación para comer el pan"], c: 0 },
        { p: "¿Qué signo usó Jesús para identificar al traidor durante la última cena?", o: ["Aquel a quien yo diere el pan mojado", "Aquel que se levante primero de la mesa", "El que se siente a mi derecha", "El que niegue conocer mi nombre"], c: 0 },
        { p: "¿A dónde se retiró Jesús a orar con angustia profunda antes de su arresto la noche de la pascua?", o: ["Al huerto de Getsemaní", "Al monte Sinaí", "A la orilla del mar de Galilea", "Al templo de Jerusalén"], c: 0 },
        { p: "¿Qué hizo el apóstol Pedro con su espada cuando los soldados arrestaron a Jesús en el huerto?", o: ["Cortó la oreja derecha a Malco, el siervo del sumo sacerdote", "Hirió al capitán de la guardia romana", "Amenazó a todos y huyó corriendo", "La rompió en el suelo por miedo"], c: 0 },
        { p: "¿Cómo sanó Jesús al siervo herido en el huerto tras el incidente de la espada?", o: ["Tocó su oreja y le sanó inmediatamente", "Le mandó a lavarse en el arroyo", "Le dio un paño sagrado", "Oró a distancia por él"], c: 0 },
        { p: "¿Ante qué tribunales religiosos fue llevado Jesús durante la noche de su arresto ilegal?", o: ["Ante Anás y el sumo sacerdote Caifás (Sanedrín)", "Ante el senado romano completo", "Ante el rey Herodes en su palacio", "Ante los ancianos de Galilea"], c: 0 },
        { p: "¿Qué señal dio el gallo tras las negaciones de Pedro en el patio del sumo sacerdote?", o: ["Cantó dos veces como Jesús le había predicho", "Cantó al amanecer anunciando el nuevo día", "No cantó porque era de noche", "Asustó a los guardias del palacio"], c: 0 },
        { p: "¿Qué hizo Judas Iscariote al ver que habían condenado a muerte a Jesús?", o: ["Devolvió las 30 monedas de plata arrepintiéndose y fue a ahorcarse", "Pidió perdón a los apóstoles llorando", "Huyó a otra región para esconderse", "Luchó contra los soldados romanos"], c: 0 },
        { p: "¿Qué compraron los principales sacerdotes con las monedas de plata devueltas por Judas?", o: ["El campo del alfarero para sepultura de extranjeros", "Incienso para el templo de Jerusalén", "Comida para los pobres de la ciudad", "Armas para la guardia del templo"], c: 0 },
        { p: "¿Cómo se llamaba el criminal liberado por la muchedumbre en lugar de Jesús por petición popular?", o: ["Barrabás", "Dimas", "Gestas", "Saulo"], c: 0 },
        { p: "¿Qué hicieron los soldados con las ropas de Jesús al pie de la cruz?", o: ["Las repartieron entre sí echando suertes", "Las quemaron en una hoguera", "Las guardaron como trofeo militar", "Se las regalaron a María"], c: 0 },
        { p: "¿Qué palabras exclamó Jesús en la cruz expresando el dolor de la separación espiritual por el pecado?", o: ["Dios mío, Dios mío, ¿por qué me has desamparado?", "Todo está consumado", "Padre, perdónalos", "Tengo sed"], c: 0 },
        { p: "¿Qué ocurrió con la cortina o velo del templo cuando Jesús exclamó su último aliento?", o: ["Se rasgó en dos de arriba a abajo", "Se dobló cuidadosamente por los sacerdotes", "Cayó al suelo hecha cenizas", "Se volvió de color rojo sangre"], c: 0 },
        { p: "¿Quiénes fueron a la tumba al amanecer del primer día de la semana encontrando la piedra removida?", o: ["Las mujeres discípulas (María Magdalena y otras)", "Los apóstoles Pedro y Juan", "Los guardias del templo", "Los fariseos incrédulos"], c: 0 }
    ],
    "Toda la Biblia": [
        { p: "¿Cuántos libros componen toda la Biblia cristiana en total?", o: ["66", "73", "27", "39"], c: 0 },
        { p: "¿Cuál es el libro más extenso de toda la Biblia?", o: ["Génesis", "Isaías", "Salmos", "Apocalipsis"], c: 2 },
        { p: "¿Cuál es el primer libro que aparece en el canon bíblico?", o: ["Éxodo", "Levítico", "Génesis", "Mateo"], c: 2 },
        { p: "¿En cuántos días creó Dios los cielos, la tierra y todo lo que en ellos hay?", o: ["7 días", "6 días", "5 días", "40 días"], c: 1 },
        { p: "¿Qué significa exactamente la palabra 'Evangelio'?", o: ["Libro santo", "Buenas nuevas o buena noticia", "Historia antigua de Dios", "Ley sagrada"], c: 1 },
        { p: "¿Cuántos libros conforman específicamente el Antiguo Testamento protestante?", o: ["27", "39", "46", "66"], c: 1 },
        { p: "¿Cuántos libros componen el Nuevo Testamento?", o: ["39", "27", "12", "4"], c: 1 },
        { p: "¿En qué idioma principal se redactó la mayor parte del Antiguo Testamento?", o: ["Hebreo", "Griego clásico", "Latín antiguo", "Arameo antiguo"], c: 0 },
        { p: "¿En qué idioma se escribió originalmente todo el Nuevo Testamento?", o: ["Hebreo antiguo", "Griego koiné", "Latín vulgar", "Inglés antiguo"], c: 1 },
        { p: "¿Quién cometió el primer homicidio registrado en la historia bíblica?", o: ["Adán", "Caín", "Lamec", "Esaú"], c: 1 },
        { p: "¿A qué hermano mató Caín en un acto de celos y envidia?", o: ["Set", "Abel", "Enoc", "Isaac"], c: 1 },
        { p: "¿Cómo se llama el gran río de Egipto cuyas aguas se convirtieron en sangre en la primera plaga?", o: ["Río Jordán", "Río Nilo", "Río Éufrates", "Río Tigris"], c: 1 },
        { p: "¿Cuál es el libro que se encuentra ubicado justo en el centro matemático de la Biblia?", o: ["Proverbios", "Salmos", "Isaías", "Job"], c: 1 },
        { p: "¿Quién fue la madre escogida por Dios para dar a luz a Jesús?", o: ["Marta", "María", "Isabel", "Ana"], c: 1 },
        { p: "¿Qué instrumento musical tocaba con destreza el joven pastor y rey David?", o: ["Trompeta", "Arpa", "Tambor", "Flauta de caña"], c: 1 },
        { p: "¿Qué ave envió Noé por segunda vez desde el arca y regresó trayendo una hoja verde de olivo?", o: ["Cuervo negro", "Paloma blanca", "Águila real", "Gorrión"], c: 1 },
        { p: "¿Cuántas tribus principales conformaban el pueblo de Israel en el Antiguo Testamento?", o: ["10", "12", "7", "40"], c: 1 },
        { p: "¿A qué gran patriarca se le conoce en la teología bíblica como 'el padre de la fe'?", o: ["Abraham", "Moisés", "David", "Pablo"], c: 0 },
        { p: "¿Quién fue el esposo terrenal de María y padre adoptivo de Jesús en Nazaret?", o: ["Zacarías", "José", "Juan el Bautista", "Simeón"], c: 1 },
        { p: "¿Qué parte de la Armadura de Dios se compara con la fe en la carta a los Efesios?", o: ["La espada del espíritu", "El escudo de la fe", "El yelmo de salvación", "El calzado del evangelio"], c: 1 },
        { p: "¿Qué profeta fue alimentado por cuervos junto a un arroyo durante una sequía severa?", o: ["Elías", "Eliseo", "Jeremías", "Amós"], c: 0 },
        { p: "¿Qué personaje bíblico fue vendido por sus hermanos y llegó a ser virrey de Egipto?", o: ["José", "Daniel", "Moisés", "David"], c: 0 },
        { p: "¿Qué mujer rescató al bebé Moisés de las aguas del río Nilo metido en una cesta?", o: ["La hija del Faraón", "Jocabed su madre", "Miriam su hermana", "Una doncella hebrea"], c: 0 },
        { p: "¿Cómo se llamaba el monte donde Dios dio la ley a Moisés?", o: ["Monte Sinaí", "Monte Carmelo", "Monte de los Olivos", "Monte Ararat"], c: 0 },
        { p: "¿Quién fue el sucesor de Moisés que introdujo al pueblo de Israel a la tierra prometida?", o: ["Josué", "Caleb", "Aarón", "Eleazar"], c: 0 },
        { p: "¿Qué reina visitó al rey Salomón para comprobar su gran sabiduría con preguntas difíciles?", o: ["La reina de Saba", "La reina Ester", "La reina Vashti", "La reina Jezabel"], c: 0 },
        { p: "¿Cuál es el libro más corto de todo el Antiguo Testamento?", o: ["Abdías", "Hageo", "Nahúm", "Jonás"], c: 0 },
        { p: "¿Cuál es el libro más corto de todo el Nuevo Testamento?", o: ["2 Juan", "3 Juan", "Judas", "Filemón"], c: 0 },
        { p: "¿Qué profeta interpretó la escritura en la pared durante la fiesta del rey Belsasar?", o: ["Daniel", "Ezequiel", "Isaías", "Jeremías"], c: 0 },
        { p: "¿Qué rey de Persia emitió el edicto para la reconstrucción del templo tras el destierro?", o: ["Ciro el Grande", "Darío", "Artajerjes", "Asuero"], c: 0 },
        { p: "¿Qué apóstol escribió el cuarto evangelio y las tres cartas que llevan su nombre?", o: ["Juan", "Pedro", "Pablo", "Mateo"], c: 0 },
        { p: "¿Quién escribió el libro de los Hechos de los Apóstoles como continuación de su evangelio?", o: ["Lucas", "Pablo", "Marcos", "Mateo"], c: 0 },
        { p: "¿Qué apóstol predicó el poderoso sermón el día de Pentecostés donde se convirtieron 3,000 personas?", o: ["Pedro", "Pablo", "Juan", "Esteban"], c: 0 },
        { p: "¿Quién fue el primer mártir cristiano apedreado en Jerusalén?", o: ["Esteban", "Santiago", "Antipas", "Pedro"], c: 0 },
        { p: "¿Qué apóstol escribió cartas a los Romanos, Corintios, Gálatas, entre otras?", o: ["Pablo", "Pedro", "Juan", "Santiago"], c: 0 },
        { p: "¿Qué libro bíblico describe la creación del universo en el principio?", o: ["Génesis", "Éxodo", "Salmos", "Job"], c: 0 },
        { p: "¿Qué libro profético del Antiguo Testamento detalla los sufrimientos del Siervo sufriente en el capítulo 53?", o: ["Isaías", "Jeremías", "Ezequiel", "Daniel"], c: 0 },
        { p: "¿Qué profeta menor pasó tres días en el vientre de un gran pez por desobedecer a Dios?", o: ["Jonás", "Amós", "Oseas", "Miqueas"], c: 0 },
        { p: "¿Qué joven pastor derrotó a un oso y a un león antes de enfrentarse a Goliat?", o: ["David", "Saúl", "Samuel", "Salomón"], c: 0 },
        { p: "¿Cómo se llamaba la suegra de Rut que experimentó amargura y luego alegría restaurada?", o: ["Noemí", "Orfa", "Abigail", "Ester"], c: 0 },
        { p: "¿Qué rey de Israel escribió muchos de los salmos de alabanza y arrepentimiento?", o: ["David", "Salomón", "Ezequías", "Josías"], c: 0 },
        { p: "¿Qué profeta vio una rueda dentro de otra rueda en su visión junto al río Quebar?", o: ["Ezequiel", "Isaías", "Daniel", "Zacarías"], c: 0 },
        { p: "¿Quién escribió la epístola que enseña que la fe sin obras está muerta?", o: ["Santiago", "Pedro", "Pablo", "Judas"], c: 0 },
        { p: "¿Qué libro del Nuevo Testamento es una carta pastoral dirigida a un joven pastor llamado Timoteo?", o: ["1 Timoteo", "Tito", "Filemón", "Hebreos"], c: 0 },
        { p: "¿Cuál es el versículo más conocido de la Biblia sobre el amor de Dios por el mundo en el evangelio de Juan?", o: ["Juan 3:16", "Salmos 23:1", "Génesis 1:1", "Apocalipsis 22:21"], c: 0 },
        { p: "¿Qué rey mandó a arrojar a Daniel al foso de los leones por envidia de los sátrapas?", o: ["Darío el medo", "Nabucodonosor", "Ciro", "Belsasar"], c: 0 },
        { p: "¿Qué jóvenes sobrevivieron al horno de fuego ardiente en Babilonia sin quemarse ni oler a humo?", o: ["Sadrac, Mesac y Abed-nego", "Pedro, Jacob y Juan", "Moisés, Aarón y Josué", "David, Natán y Gad"], c: 0 },
        { p: "¿Qué profeta desafió a los profetas de Baal en el monte Carmelo haciendo caer fuego del cielo?", o: ["Elías", "Eliseo", "Samuel", "Natán"], c: 0 },
        { p: "¿Qué profeta sanó su capa y multiplicó aceite y pan en el Antiguo Testamento?", o: ["Eliseo", "Elías", "Isaías", "Jeremías"], c: 0 },
        { p: "¿Qué personaje bíblico perdió toda su riqueza y salud pero mantuvo su integridad ante Dios?", o: ["Job", "Abraham", "Isaac", "Jacob"], c: 0 },
        { p: "¿Qué libro de la sabiduría bíblica comienza diciendo 'El principio de la sabiduría es el temor de Jehová'?", o: ["Proverbios", "Salmos", "Eclesiastés", "Job"], c: 0 },
        { p: "¿Cómo se llama el famoso salmo que comienza diciendo 'Jehová es mi pastor; nada me faltará'?", o: ["Salmo 23", "Salmo 91", "Salmo 1", "Salmo 100"], c: 0 },
        { p: "¿Qué salmo habla de la morada bajo la sombra del Omnipotente diciendo 'No temerás el terror nocturno'?", o: ["Salmo 91", "Salmo 23", "Salmo 8", "Salmo 121"], c: 0 },
        { p: "¿Qué profeta predijo que el lugar del nacimiento del Mesías sería Belén?", o: ["Miqueas", "Isaías", "Jeremías", "Amós"], c: 0 },
        { p: "¿Qué rey mandó a construir el primer templo de Jerusalén consagrado a Dios?", o: ["Salomón", "David", "Ezequías", "Josías"], c: 0 },
        { p: "¿Qué profeta lloró copiosamente por la destrucción de la ciudad de Jerusalén?", o: ["Jeremías", "Ezequiel", "Daniel", "Isaías"], c: 0 },
        { p: "¿Quién fue el primer mártir de la iglesia cristiana primitiva en Hechos de los Apóstoles?", o: ["Esteban", "Santiago", "Pedro", "Pablo"], c: 0 },
        { p: "¿Qué apóstol escribió un libro apocalíptico completo lleno de visiones celestiales en la isla de Patmos?", o: ["Juan", "Pedro", "Pablo", "Santiago"], c: 0 },
        { p: "¿Qué nombre recibe el libro que detalla los viajes y la historia inicial de la iglesia cristiana tras la resurrección de Jesús?", o: ["Hechos de los Apóstoles", "Romanos", "Apocalipsis", "Gálatas"], c: 0 },
        { p: "¿Qué personaje del Nuevo Testamento era un fariseo prominente y doctor de la ley que defendió a los apóstoles en el Sanedrín?", o: ["Gamaliel", "Nicodemo", "Caifás", "Anás"], c: 0 },
        { p: "¿Qué joven predicador enfermizo recibió consejos de Pablo de tomar un poco de vino por causa de su estómago?", o: ["Timoteo", "Tito", "Marcos", "Lucas"], c: 0 },
        { p: "¿Qué colaborador de Pablo fue dejado en la isla de Creta para ordenar ancianos en cada ciudad?", o: ["Tito", "Timoteo", "Onésimo", "Tíquico"], c: 0 },
        { p: "¿Qué esclavo fugitivo se convirtió en hermano en la fe y fue recomendado por Pablo a su amo Filemón?", o: ["Onésimo", "Tíquico", "Erasto", "Creso"], c: 0 },
        { p: "¿Qué tesoro espiritual describe la carta a los Gálatas compuesto por nueve virtudes del Espíritu Santo?", o: ["El fruto del Espíritu", "Los dones ministeriales", "Las armaduras celestiales", "Las bienaventuranzas"], c: 0 },
        { p: "¿Qué capítulo de la Biblia es conocido como el capítulo de la fe, enumerando a los héroes antiguos de la confianza en Dios?", o: ["Hebreos 11", "1 Corintios 13", "Romanos 8", "Gálatas 5"], c: 0 },
        { p: "¿Qué capítulo del Nuevo Testamento describe la seguridad eterna del creyente diciendo 'si Dios es por nosotros, ¿quién contra nosotros?'?", o: ["Romanos 8", "Juan 3", "Efesios 6", "1 Juan 4"], c: 0 },
        { p: "¿Qué profeta del Antiguo Testamento vio al Señor sentado en un trono alto y sublime con serafines clamando 'Santo, santo, santo'?", o: ["Isaías", "Ezequiel", "Jeremías", "Daniel"], c: 0 },
        { p: "¿Qué río cruzó el profeta Eliseo golpeando las aguas con el manto de Elías y dividiéndolas?", o: ["Río Jordán", "Río Éufrates", "Río Nilo", "Río Jaboc"], c: 0 },
        { p: "¿Cómo se llamaba la madre del profeta Samuel que cantó un hermoso cántico de alabanza a Dios?", o: ["Ana", "Abigail", "Noemí", "Ester"], c: 0 },
        { p: "¿Qué juez de Israel hizo un voto imprudente que afectó a su única hija tras ganar una gran batalla?", o: ["Jefté", "Gedeón", "Sansón", "Otoniel"], c: 0 },
        { p: "¿Qué mujer valiente del Antiguo Testamento detuvo la furia de David con generosos regalos y prudencia antes de que este matara a su esposo Nabal?", o: ["Abigail", "Ester", "Rut", "Débora"], c: 0 },
        { p: "¿Qué rey de Judá hizo pozos, fortaleció murallas y clamó a Dios en gran batalla contra una enorme multitud de etíopes?", o: ["Asa", "Josafat", "Ezequías", "Josías"], c: 0 },
        { p: "¿Qué rey piadoso celebró una gran pascua en Jerusalén como no se había visto desde los días de Samuel el profeta?", o: ["Josías", "Ezequías", "David", "Salomón"], c: 0 },
        { p: "¿Qué profeta menor predijo que derramaría Dios su Espíritu sobre toda carne en los últimos días?", o: ["Joel", "Amós", "Oseas", "Malaquías"], c: 0 },
        { p: "¿Qué profeta cuestionó a Dios por usar a una nación más inicua que Judá (los caldeos) para castigar a su pueblo?", o: ["Habacuc", "Sofonías", "Hageo", "Nahúm"], c: 0 },
        { p: "¿Qué profeta pronunció fuertes juicios sobre el día de ira de Jehová en el capítulo 1 de su libro?", o: ["Sofonías", "Habacuc", "Malaquías", "Amós"], c: 0 },
        { p: "¿Qué profeta escribió 'Mas el justo vivirá por su fe'?", o: ["Habacuc", "Isaías", "Jeremías", "Miqueas"], c: 0 },
        { p: "¿Qué libro del Nuevo Testamento advierte intensamente contra los falsos maestros comparándolos con fuentes sin agua y nubes empujadas por la tormenta?", o: ["Epístola de Judas", "2 Pedro", "1 Juan", "Santiago"], c: 0 },
        { p: "¿Qué apóstol escribió 'Dios es amor; y el que permanece en amor, permanece en Dios, y Dios en él'?", o: ["Juan", "Pedro", "Pablo", "Santiago"], c: 0 },
        { p: "¿Qué nos enseña la Biblia en el libro de Proverbios sobre la corrección y la disciplina hacia los hijos?", o: ["El que detiene el rodillo, a su hijo aborrece; mas el que lo ama, desde temprano lo corrige", "La disciplina no sirve para los jóvenes modernos", "Dejad que los niños crezcan sin reglas estrictas", "La corrección se quita al cumplir la mayoría de edad"], c: 0 },
        { p: "¿Qué enseña el libro de Eclesiastés acerca de acordarse del Creador?", o: ["Acuérdate de tu Creador en los días de tu juventud, antes que vengan los días malos", "Acuerdate de Dios únicamente al final de tu vida", "La juventud es para disfrutar sin pensar en el Creador", "Dios solo se acuerda de los ancianos sabios"], c: 0 },
        { p: "¿Qué gran promesa da el libro de Josué sobre la meditación diaria en la ley de Dios?", o: ["Nunca se apartará de tu boca este libro de la ley... para que guardes y hagas conforme a todo... porque entonces harás prosperar tu camino", "Tendrás riquezas materiales garantizadas en el mundo", "Nunca tendrás ninguna clase de prueba ni problema físico", "Serás el rey de todas las naciones vecinas"], c: 0 },
        { p: "¿Qué gran mandamiento resumió Jesús como el primero y más importante de toda la ley y los profetas?", o: ["Amarás al Señor tu Dios con todo tu corazón, y con toda tu alma, y con toda tu mente", "Amarás a tu prójimo exactamente igual que a ti mismo", "Guardarás todos los sábados sin encender fuego", "Pagarás tus impuestos al templo a tiempo"], c: 0 },
        { p: "¿Cuál es el segundo mandamiento semejante al primero según las palabras de Jesús?", o: ["Amarás a tu prójimo como a ti mismo", "No robarás ni dirás falso testimonio jamás", "Honrarás a tu padre y a tu madre siempre", "No codiciarás los bienes ajenos de nadie"], c: 0 },
        { p: "¿Qué nos dice el apóstol Pablo en Romanos sobre todas las cosas y los que aman a Dios?", o: ["Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien", "Todas las cosas malas desaparecerán de la tierra para los santos", "Los creyentes nunca sufrirán persecución ni dolor físico", "El éxito económico viene para todos los que oran mucho"], c: 0 },
        { p: "¿Qué hermosa instrucción da Filipenses sobre la ansiedad y la preocupación en la vida diaria?", o: ["Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios en toda oración", "Preocúpate el doble para resolver tus problemas rápido", "Guarda silencio y no le cuentes tus cargas a nadie", "La ansiedad se quita durmiendo muchas horas al día"], c: 0 },
        { p: "¿Qué paz promete la misma carta a los Filipenses para los que oran confiados?", o: ["Y la paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones", "Una paz terrenal con todos los ejércitos vecinos", "La ausencia total de enemigos políticos", "Riquezas y tranquilidad material abundante"], c: 0 },
        { p: "¿Cómo define la carta a los Hebreos lo que es la fe en su capítulo 11?", o: ["Es la certeza de lo que se espera, la convicción de lo que no se ve", "Es el conocimiento intelectual de todas las escrituras sagradas", "Es ver milagros grandes con los ojos físicos todos los días", "Es sentir emociones fuertes en las reuniones de culto"], c: 0 },
        { p: "¿Qué nos dice la primera carta de Juan acerca de confesar nuestros pecados a Dios?", o: ["Si confesamos nuestros pecados, él es fiel y justo para perdonar nuestros pecados", "Si ocultamos nuestras faltas nadie se dará cuenta jamás", "Dios perdona sin necesidad de arrepentimiento sincero", "Los pecados graves no se pueden perdonar nunca"], c: 0 },
        { p: "¿Qué gran promesa final deja el libro de Mateo antes de que Jesús ascienda a los cielos?", o: ["Y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo. Amén", "Volveré dentro de tres años exactos a reinar", "Construyan una gran muralla en Jerusalén para protegerse", "Guarden silencio y esperen en secreto"], c: 0 }
    ]
};

module.exports = baseDeDatos;